<?php

/**
 * @file
 * AV Products module.
 */

define('AVEXPENSES_MODULE_PATH', drupal_get_path('module', 'avexpenses'));

//require_once 'inc/helpers.inc';
module_load_include('inc', 'avexpenses', 'inc/helpers');

/**
 * Implementation of hook_menu().
 */
function avexpenses_menu() {
  $items['av/expenses'] = array(
    'title' => 'Expenses',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('avexpenses_home_form'),
    'access callback' => 'user_is_logged_in',
    'menu_name' => 'av',
    'expanded' => TRUE,
  );
  $items['av/expenses/purchase-order/new'] = array(
    'title' => 'New Purchase Order',
    'page callback' => 'avexpenses_po_form_load',
    'page arguments' => array(NULL),
    'access callback' => 'user_is_logged_in',
    'type' => MENU_LOCAL_TASK,
    'file' => 'inc/po.inc',
    'menu_name' => 'av',
    'expanded' => TRUE,
  );
  return $items;
}

/**
 * Implementation of hook_theme().
 *
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 * @return array
 */
function avexpenses_theme($existing, $type, $theme, $path) {
  $themes = array();

  $template_path = $path . '/templates';
  $theme_names = array(
    'avexpenses_po_form',
  );
  foreach ($theme_names as $theme_name) {
    $themes[$theme_name] = array(
      'render element' => 'form',
      'template' => str_replace('_', '-', $theme_name),
      'path' => $template_path,
    );
  }

  $themes['avexpenses_po_mail'] = array(
    'variables' => array(),
    'template' => 'avexpenses-po-mail',
    'path' => $template_path,
  );

  return $themes;
}

/**
 * Expenses List page.
 * @param $form
 * @param $form_state
 * @return array
 */
function avexpenses_home_form($form, &$form_state) {
  $form['new_po'] = array('#markup' => l('New purchase order', 'av/expenses/purchase-order/new', array('attributes' => array('class' => array('uk-button', 'uk-button-primary')))));
  return $form;
}

/**
 * Implementation of hook_mail().
 * @param $key
 * @param $message
 * @param $params
 */
function avexpenses_mail($key, &$message, $params) {
  switch ($key) {
    case 'po':
      $message['subject'] = t('Purchase order from @site_name', array('@site_name' => variable_get('site_name', 'UCT')));
      $message['body'] = theme('avexpenses_po_mail', $params);
      break;
  }
}
