<?php

/**
 * @file
 * AV Products module.
 */

define('AVPRODUCTS_MODULE_PATH', drupal_get_path('module', 'avproducts'));

require_once 'inc/helpers.inc';

/**
 * Implementation of hook_menu().
 */
function avproducts_menu() {
  $items['av/products'] = array(
    'title' => 'Products',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('avproducts_home_form'),
    'access callback' => 'user_is_logged_in',
    'menu_name' => 'av',
    'expanded' => TRUE,
  );
  $items['av/products/add'] = array(
    'title' => 'New Product',
    'page callback' => 'avproducts_product_form_load',
    'page arguments' => array(NULL),
    'access callback' => 'user_is_logged_in',
    'type' => MENU_CALLBACK,
    'file' => 'inc/crud.inc',
  );
  $items['av/products/%avproduct/edit'] = array(
    'title' => 'Edit Product',
    'page callback' => 'avproducts_product_form_load',
    'page arguments' => array(2),
    'access callback' => 'user_is_logged_in',
    'type' => MENU_CALLBACK,
    'file' => 'inc/crud.inc',
  );
  $items['av/products/%avproduct/delete'] = array(
    'title' => 'Delete Product',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('avproducts_product_delete_confirm_form', 2),
    'access callback' => 'user_is_logged_in',
    'type' => MENU_CALLBACK,
    'file' => 'inc/crud.inc',
  );
  return $items;
}

/**
 * Implementation of hook_theme().
 *
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 * @return array
 */
function avproducts_theme($existing, $type, $theme, $path) {
  $forms_template_path = $path . '/templates/forms';
  $form_names = array(
    'avproducts_product_form',
    'avproducts_home_form',
  );

  $theme_forms = array();
  foreach ($form_names as $form_name) {
    $theme_forms[$form_name] = array(
      'render element' => 'form',
      'template' => str_replace('_', '-', $form_name),
      'path' => $forms_template_path,
    );
  }

  return $theme_forms;
}

/**
 * Products homepage form.
 *
 * @param $form
 * @param $form_state
 * @return array
 */
function avproducts_home_form($form, &$form_state) {
//  drupal_add_js('sites/all/libraries/ag-grid/ag-grid.min.js');
//  drupal_add_js(AVPRODUCTS_MODULE_PATH . '/js/avproducts.js');

  $btn_options = array('attributes' => array('class' => AV_STYLE_CLASS_BTN . ' ' . AV_STYLE_CLASS_BTN_PRIMARY));
  $form['new_button'] = array('#markup' => l('New product', 'av/products/add', $btn_options));

  $header = array(
    array('data' => 'Name', 'field' => 'title'),
    array('data' => 'Category', 'field' => 'category_id'),
    array('data' => 'UOM', 'field' => 'uom_id'),
    array('data' => 'Description', 'field' => 'description'),
    array('data' => 'Sales price', 'field' => 'price'),
    array('data' => 'Cost', 'field' => 'cost'),
    array('data' => 'Qty.', 'field' => 'qty'),
    '&nbsp;',
  );

  $rows = array();
  $result = db_select('avtbl_products', 'ap')
    ->fields('ap')
    ->extend('PagerDefault')
    ->extend('TableSort')
    ->limit(10)
    ->orderByHeader($header)
    ->execute();

  $action_links_all = array();
  foreach ($result as $row) {
    $action_links = array('links' => array(
      'edit' => array('title' => 'edit', 'href' => 'av/products/' . $row->id . '/edit', 'icon_kedy' => 'edit'),
      'delete' => array('title' => 'delete', 'href' => 'av/products/' . $row->id . '/delete', 'icond_key' => 'remove', 'query' => drupal_get_destination()),
    ));

    $action_links_all[] = $action_links;
    $actions_html = theme('links__bare', $action_links);
    $rows[] = array(
    'data' => array(
      'display_name' => check_plain($row->title),
      'category' => $row->category_id,
      'uom' => $row->uom_id,
      'description' => check_plain($row->description),
      'price' => $row->price,
      'cost' => $row->cost,
      'qty' => $row->qty,
      'actions' => $actions_html,
    ),
    'class' => array('uk-table-middle'),
    );
  }

  $table_attributes = array('id' => 'products-list-table');
  if (empty($rows)) {
    $table_markup = '<p>Nothing recorded yet.</p>';
  }
  else {
    $table_markup = theme('table', array('header' => $header, 'rows' => $rows, 'attributes' => $table_attributes, 'action_links_all' => $action_links_all));
  }
  $form['table']['#markup'] = $table_markup;
  $form['pager']['#markup'] = theme('pager', array('tags' => array()));
//$form['#after_build'] = array('avproducts_home_form_after_build');
//  $form['ag-grid']['#markup'] = '<div id="myGrid" style="height: 300px;" class="ag-fresh"></div>';
  return $form;
}

function avproducts_home_form_after_build($form, &$form_state) {
  dpm('f');
  dpm($form);
  return $form;
}
