<?php

/**
 * @file
 * AVS Customers module.
 */

/**
 * Implementation of hook_menu().
 */
function avscustomers_menu() {
  $items['a/customers'] = array(
    'title' => 'Customers',
    'page callback' => 'avscustomers_home',
    'access arguments' => array('access content'),
    'menu_name' => 'avs',
    'expanded' => TRUE,
  );
  return $items;
}

/**
 * Customers homepage callback.
 */
function avscustomers_home() {
  return 'Customers!';
}
