<?php

/**
 * @file
 * AV Products module.
 */

define('AVPURCHASE_MODULE_PATH', drupal_get_path('module', 'avpurchase'));

//require_once 'inc/helpers.inc';
module_load_include('inc', 'avpurchase', 'inc/helpers');

/**
 * Implementation of hook_menu().
 */
function avpurchase_menu() {
  $items['av/purchase'] = array(
    'title' => 'Purchase',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('avpurchase_home_form'),
    'access callback' => 'user_is_logged_in',
    'menu_name' => 'av',
    'expanded' => TRUE,
  );
  $items['av/purchase/po/new'] = array(
    'title' => 'New Purchase Order',
    'page callback' => 'avpurchase_po_form_load',
    'page arguments' => array(NULL),
    'access callback' => 'user_is_logged_in',
    'type' => MENU_LOCAL_TASK,
    'file' => 'inc/po.inc',
    'weight' => 10,
  );
  //$items['av/purchase/po/%avpurchase_po/view'] = array(
  //  'title' => 'View Purchase Order',
  //  'page callback' => 'avpurchase_po_form_load',
  //  'page arguments' => array(3),
  //  'access callback' => 'user_is_logged_in',
  //  //'type' => MENU_LOCAL_TASK,
  //  'file' => 'inc/po.inc',
  //  'weight' => 0,
  //);
  return $items;
}

/**
 * Implementation of hook_theme().
 *
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 * @return array
 */
function avpurchase_theme($existing, $type, $theme, $path) {
  $themes = array();

  $template_path = $path . '/templates';

  // FORMS.
  $theme_names = array(
    'avpurchase_po_form',
  );
  foreach ($theme_names as $theme_name) {
    $themes[$theme_name] = array(
      'render element' => 'form',
      'template' => str_replace('_', '-', $theme_name),
      'path' => $template_path,
    );
  }

  // OTHERS.
  $theme_names = array(
    'avpurchase_po_mail',
    'avpurchase_po_mail_table',
  );
  foreach ($theme_names as $theme_name) {
    $themes[$theme_name] = array(
      'variables' => array(),
      'template' => str_replace('_', '-', $theme_name),
      'path' => $template_path,
    );
  }

  return $themes;
}

/**
 * Purchase List page.
 * @param $form
 * @param $form_state
 * @return array
 */
function avpurchase_home_form($form, &$form_state) {
  $form['new_po'] = array('#markup' => l('New purchase order', 'av/purchase/po/new', array('attributes' => array('class' => array('uk-button', 'uk-button-primary')))));
  return $form;
}

/**
 * Implementation of hook_mail().
 * @param $key
 * @param $message
 * @param $params
 */
function avpurchase_mail($key, &$message, $params) {
  switch ($key) {
    case 'po':
      $message['subject'] = t('Purchase Order from @site_name - P.O.# @po_num', array('@po_num' => $params['po_num'], '@site_name' => variable_get('site_name', 'UCT')));
      $message['body'] = theme('avpurchase_po_mail', $params);
      // Save a copy.
      //$message['headers']['CC'] = 'ucaretrading@gmail.com';
      break;
  }
}
