<?php

/**
 * @file
 * AV Products module.
 */

define('AVTRANS_MODULE_PATH', drupal_get_path('module', 'avtrans'));

//require_once 'inc/helpers.inc';
module_load_include('inc', 'avtrans', 'inc/helpers');

/**
 * Implementation of hook_menu().
 */
function avtrans_menu() {
  $items['av/transactions'] = array(
    'title' => 'Transaction',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('avtrans_home_form'),
    'access callback' => 'user_is_logged_in',
    'menu_name' => 'av',
    'expanded' => TRUE,
  );
  $items['av/po/new'] = array(
    'title' => 'New Purchase Order',
    'page callback' => 'avtrans_po_form_load',
    'page arguments' => array(NULL),
    'access callback' => 'user_is_logged_in',
    'type' => MENU_CALLBACK,
    'file' => 'inc/po.form.inc',
    'weight' => 10,
  );
  //$items['av/po/%avtrans_po/view'] = array(
  //  'title' => 'View Purchase Order',
  //  'page callback' => 'avtrans_po_form_load',
  //  'page arguments' => array(3),
  //  'access callback' => 'user_is_logged_in',
  //  //'type' => MENU_LOCAL_TASK,
  //  'file' => 'inc/po.form.inc',
  //  'weight' => 0,
  //);
  $items['av/gr/new'] = array(
    'title' => 'Receive items',
    'page callback' => 'avtrans_gr_form_load',
    'page arguments' => array(NULL),
    'access callback' => 'user_is_logged_in',
    'type' => MENU_CALLBACK,
    'file' => 'inc/gr/gr.form.inc',
    'weight' => 10,
  );
  $items['av/sales-order/new'] = array(
    'title' => 'New Sales Order',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('avtrans_so_form', NULL),
    'access callback' => 'user_is_logged_in',
    'type' => MENU_CALLBACK,
    'file' => 'inc/so.form.inc',
    'weight' => 10,
  );
  $items['av/delivery/new'] = array(
    'title' => 'Delivery',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('avtrans_delivery_form', NULL),
    'access callback' => 'user_is_logged_in',
    'type' => MENU_CALLBACK,
    'file' => 'inc/delivery/delivery.form.inc',
    'weight' => 10,
  );
  return $items;
}

/**
 * Implementation of hook_theme().
 *
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 * @return array
 */
function avtrans_theme($existing, $type, $theme, $path) {
  $themes = array();

  $template_path = $path . '/templates';

  // FORMS.
  $theme_names = array(
    'avtrans_item_list_form',
  );
  foreach ($theme_names as $theme_name) {
    $themes[$theme_name] = array(
      'render element' => 'form',
      'template' => str_replace('_', '-', $theme_name),
      'path' => $template_path,
    );
  }

  // OTHERS.
  $theme_names = array(
    'avtrans_po_mail',
    'avtrans_po_mail_table',
  );
  foreach ($theme_names as $theme_name) {
    $themes[$theme_name] = array(
      'variables' => array(),
      'template' => str_replace('_', '-', $theme_name),
      'path' => $template_path,
    );
  }

  return $themes;
}

/**
 * Transaction List page.
 * @param $form
 * @param $form_state
 * @return array
 */
function avtrans_home_form($form, &$form_state) {
  $form['new_po'] = array('#markup' => l('New purchase order', 'av/po/new', array('attributes' => array('class' => array('uk-button', 'uk-button-primary')))));
  $form['new_gr'] = array('#markup' => l('Receive items', 'av/gr/new', array('attributes' => array('class' => array('uk-button', 'uk-button-primary', 'uk-margin-left')))));
  $form['new_so'] = array('#markup' => l('New sales order', 'av/sales-order/new', array('attributes' => array('class' => array('uk-button', 'uk-button-primary', 'uk-margin-left')))));
  $form['new_dr'] = array('#markup' => l('New delivery', 'av/delivery/new', array('attributes' => array('class' => array('uk-button', 'uk-button-primary', 'uk-margin-left')))));
  return $form;
}

/**
 * Implementation of hook_mail().
 * @param $key
 * @param $message
 * @param $params
 */
function avtrans_mail($key, &$message, $params) {
  switch ($key) {
    case 'po':
      $message['subject'] = t('Purchase Order from @site_name - P.O.# @po_num', array('@po_num' => $params['po_num'], '@site_name' => variable_get('site_name', 'UCT')));
      $message['body'] = theme('avtrans_po_mail', $params);
      // Save a copy.
      //$message['headers']['CC'] = 'ucaretrading@gmail.com';
      break;
  }
}
