<?php

/**
 * @file
 * AV Products module.
 */

define('AVTRANS_MODULE_PATH', drupal_get_path('module', 'avtrans'));

//require_once 'inc/helpers.inc';
module_load_include('inc', 'avtrans', 'inc/helpers');

define('AVTRANS_RETURN_TYPE_RUD', 1);
define('AVTRANS_RETURN_TYPE_RS', 2);

/**
 * Implementation of hook_menu().
 */
function avtrans_menu() {
  $items['av/transactions'] = array(
    'title' => 'Transactions',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('avtrans_transaction_home_form'),
    'access callback' => 'user_is_logged_in',
    'menu_name' => 'av',
    'expanded' => TRUE,
  );
  $items['av/po'] = array(
    'title' => 'Transactions',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('avtrans_transaction_home_form'),
    'access callback' => 'user_is_logged_in',
  );
  $items['av/po/new'] = array(
    'title' => 'New Purchase Order',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('avtrans_po_form', NULL),
    'access callback' => 'user_is_logged_in',
    'type' => MENU_LOCAL_TASK,
    'file' => 'inc/po.form.inc',
    'weight' => 10,
    //'tab_parent' => 'av/transactions',
    //'tab_root' => 'av/transactions',
  );
  $items['av/po/%avtrans_po/view'] = array(
    'title' => 'View Purchase Order',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('avtrans_po_form', 2, TRUE),
    'access callback' => 'user_is_logged_in',
    'type' => MENU_LOCAL_TASK,
    'file' => 'inc/po.form.inc',
    'weight' => 0,
    //'tab_parent' => 'av/transactions',
    //'tab_root' => 'av/transactions',
  );
  //$items['av/po/%avtrans_po/edit'] = array(
  //  'title' => 'Edit Purchase Order',
  //  'page callback' => 'drupal_get_form',
  //  'page arguments' => array('avtrans_po_form', 2),
  //  'access callback' => 'user_is_logged_in',
  //  'type' => MENU_LOCAL_TASK,
  //  'file' => 'inc/po.form.inc',
  //  'weight' => 1,
  //);
  $items['av/gr'] = array(
    'title' => 'Transactions',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('avtrans_transaction_home_form'),
    'access callback' => 'user_is_logged_in',
  );
  $items['av/gr/new'] = array(
    'title' => 'Receive items',
    'page callback' => 'avtrans_gr_form_load',
    'page arguments' => array(NULL),
    'access callback' => 'user_is_logged_in',
    'type' => MENU_LOCAL_TASK,
    'file' => 'inc/gr/gr.form.inc',
    'weight' => 10,
    //'tab_parent' => 'av/transactions',
    //'tab_root' => 'av/transactions',
  );
  $items['av/gr/%avtrans_gr/view'] = array(
    'title' => 'View Received Items',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('avtrans_gr_form', 2, TRUE),
    'access callback' => 'user_is_logged_in',
    'type' => MENU_LOCAL_TASK,
    'file' => 'inc/gr/gr.form.inc',
    'weight' => 0,
    //'tab_parent' => 'av/transactions',
    //'tab_root' => 'av/transactions',
  );
  $items['av/sales-order'] = array(
    'title' => 'Transactions',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('avtrans_transaction_home_form'),
    'access callback' => 'user_is_logged_in',
  );
  $items['av/sales-order/new'] = array(
    'title' => 'New Sales Order',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('avtrans_so_form', NULL),
    'access callback' => 'user_is_logged_in',
    'type' => MENU_LOCAL_TASK,
    'file' => 'inc/so.form.inc',
    'weight' => 10,
    //'tab_parent' => 'av/transactions',
    //'tab_root' => 'av/transactions',
  );
  $items['av/sales-order/%avtrans_so/view'] = array(
    'title' => 'View Sales Order',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('avtrans_so_form', 2, TRUE),
    'access callback' => 'user_is_logged_in',
    'type' => MENU_LOCAL_TASK,
    'file' => 'inc/so.form.inc',
    'weight' => 0,
    //'tab_parent' => 'av/transactions',
    //'tab_root' => 'av/transactions',
  );
  $items['av/delivery'] = array(
    'title' => 'Transactions',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('avtrans_transaction_home_form'),
    'access callback' => 'user_is_logged_in',
  );
  $items['av/delivery/new'] = array(
    'title' => 'New Delivery',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('avtrans_delivery_form', NULL),
    'access callback' => 'user_is_logged_in',
    'type' => MENU_LOCAL_TASK,
    'file' => 'inc/delivery/delivery.form.inc',
    'weight' => 10,
    //'tab_parent' => 'av/transactions',
    //'tab_root' => 'av/transactions',
  );
  $items['av/delivery/%avtrans_dr/view'] = array(
    'title' => 'View Delivery',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('avtrans_delivery_form', 2, TRUE),
    'access callback' => 'user_is_logged_in',
    'type' => MENU_LOCAL_TASK,
    'file' => 'inc/delivery/delivery.form.inc',
    'weight' => 0,
    //'tab_parent' => 'av/transactions',
    //'tab_root' => 'av/transactions',
  );
  $items['av/ret'] = array(
    'title' => 'Transactions',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('avtrans_transaction_home_form'),
    'access callback' => 'user_is_logged_in',
  );
  $items['av/ret/new'] = array(
    'title' => 'New sales return',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('avtrans_ret_form', NULL),
    'access callback' => 'user_is_logged_in',
    'type' => MENU_LOCAL_TASK,
    'file' => 'inc/ret/ret.form.inc',
    'weight' => 10,
    //'tab_parent' => 'av/transactions',
    //'tab_root' => 'av/transactions',
  );
  $items['av/ret/%avtrans_ret/view'] = array(
    'title' => 'View sales return',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('avtrans_ret_form', 2, TRUE),
    'access callback' => 'user_is_logged_in',
    'type' => MENU_LOCAL_TASK,
    'file' => 'inc/ret/ret.form.inc',
    'weight' => 0,
    //'tab_parent' => 'av/transactions',
    //'tab_root' => 'av/transactions',
  );
  $items['av/rept'] = array(
    'title' => 'Transactions',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('avtrans_transaction_home_form'),
    'access callback' => 'user_is_logged_in',
  );
  $items['av/rept/new'] = array(
    'title' => 'New purchase return',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('avtrans_rept_form', NULL),
    'access callback' => 'user_is_logged_in',
    'type' => MENU_LOCAL_TASK,
    'file' => 'inc/rept/rept.form.inc',
    'weight' => 10,
    //'tab_parent' => 'av/transactions',
    //'tab_root' => 'av/transactions',
  );
  $items['av/rept/%avtrans_rept/view'] = array(
    'title' => 'View purchase return',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('avtrans_rept_form', 2, TRUE),
    'access callback' => 'user_is_logged_in',
    'type' => MENU_LOCAL_TASK,
    'file' => 'inc/rept/rept.form.inc',
    'weight' => 0,
    //'tab_parent' => 'av/transactions',
    //'tab_root' => 'av/transactions',
  );
  return $items;
}

/**
 * Implementation of hook_theme().
 *
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 * @return array
 */
function avtrans_theme($existing, $type, $theme, $path) {
  $themes = array();

  $template_path = $path . '/templates';

  // FORMS.
  $theme_names = array(
    'avtrans_item_list_form',
    'avtrans_transaction_list_filter_form',
  );
  foreach ($theme_names as $theme_name) {
    $themes[$theme_name] = array(
      'render element' => 'form',
      'template' => str_replace('_', '-', $theme_name),
      'path' => $template_path,
    );
  }

  // OTHERS.
  $theme_names = array(
    'avtrans_po_mail',
    'avtrans_po_mail_table',
  );
  foreach ($theme_names as $theme_name) {
    $themes[$theme_name] = array(
      'variables' => array(),
      'template' => str_replace('_', '-', $theme_name),
      'path' => $template_path,
    );
  }

  return $themes;
}

/**
 * Transaction List page.
 * @param $form
 * @param $form_state
 * @return array
 */
function avtrans_transaction_home_form($form, &$form_state) {
// Set autocomplete off.
  $form['#attributes']['autocomplete'] = 'off';

  $form['new_po'] = array('#markup' => l('New purchase order', 'av/po/new', array('attributes' => array('class' => array('uk-button', 'uk-button-primary')))));
  $form['new_gr'] = array('#markup' => l('Receive items', 'av/gr/new', array('attributes' => array('class' => array('uk-button', 'uk-button-primary', 'uk-margin-left')))));
  $form['new_rept'] = array('#markup' => l('New purchase return', 'av/rept/new', array('attributes' => array('class' => array('uk-button', 'uk-button-primary', 'uk-margin-left')))));
  $form['new_so'] = array('#markup' => l('New sales order', 'av/sales-order/new', array('attributes' => array('class' => array('uk-button', 'uk-button-success', 'uk-margin-left')))));
  $form['new_dr'] = array('#markup' => l('New delivery', 'av/delivery/new', array('attributes' => array('class' => array('uk-button', 'uk-button-success', 'uk-margin-left')))));
  $form['new_ret'] = array('#markup' => l('New sales return', 'av/ret/new', array('attributes' => array('class' => array('uk-button', 'uk-button-success', 'uk-margin-left')))));

  $form['transaction_list'] = avtrans_transaction_list_form($form, $form_state);
  return $form;
}

/**
 * Implementation of hook_mail().
 * @param $key
 * @param $message
 * @param $params
 */
function avtrans_mail($key, &$message, $params) {
  switch ($key) {
    case 'po':
      $message['subject'] = t('Purchase Order from @site_name - P.O.# @po_num', array('@po_num' => $params['po_num'], '@site_name' => variable_get('site_name', 'UCT')));
      $message['body'] = theme('avtrans_po_mail', $params);
      // Save a copy.
      //$message['headers']['CC'] = 'ucaretrading@gmail.com';
      break;
  }
}

function avtrans_transaction_list_form($form, &$form_state, $options = array()) {
  $form = array(
    '#visible_in_view_mode' => TRUE,
    //'#prefix' => '<div>'
  );

  if (empty($options['#hide_filter_form'])) {
    $form['transaction_list_filter'] = avtrans_transaction_list_filter_form(NULL, $form_state);
    $form['transaction_list_filter']['search_text']['#attributes']['placeholder'] = 'search agent, customer, vendor';
  }
  $client_header = 'Customer / Vendor';
  //if (arg(1) == 'vendors') {
  //  $client_header = 'Vendor';
  //}
  //elseif (arg(1) == 'customers') {
  //  $client_header = 'Customer';
  //}
  $header = array(
    array('data' => 'Type'),
    array('data' => 'Transaction #'),
    array('data' => $client_header),
    array('data' => 'Date'),
    array('data' => 'Agent'),
  );

  $required_filter_query = empty($options['#filter_query']) ? array() : $options['#filter_query'];
  $filter_query = empty($form_state['values']['avtrans_tl_filter']['filter_query']) ? array() : $form_state['values']['avtrans_tl_filter']['filter_query'];
  $filter_query = array_merge_recursive($filter_query, $required_filter_query);
  $where = empty($filter_query['where']) ? array() : $filter_query['where'];
  $args = empty($filter_query['args']) ? array() : $filter_query['args'];
  $transactions = avtrans_transactions_query_load($where, $args, '15');
  $index = 0;
  foreach ($transactions as $row) {
    $index++;
    $transaction_type = avtrans_transaction_types($row->transaction_type);
    $view_path = "{$transaction_type['base_path']}/$row->transaction_id/view";
    $rows[$index] = array(
      'data' => array(
        l($transaction_type['title'], $view_path),
        l($row->transaction_id, $view_path),
        $rows[$index]['data'][] = check_plain($row->display_name),
        l(format_date($row->transaction_date, 'custom', 'M d, Y h:i a'), $view_path),
        check_plain($row->agent_name),
      ),
      'class' => array('uk-table-middle'),
    );
  }

  $table_attributes = array(
    'id' => 'transaction-list-table',
    'class' => array(),
  );
  if (empty($rows)) {
    $table_markup = '<div class="uk-margin-top uk-text-muted">No match found.</div>';
  }
  else {
    $table_markup = theme('table', array('header' => $header, 'rows' => $rows, 'attributes' => $table_attributes));
  }
  $form['transaction_list_table']['#markup'] = '<div id="transaction-list-table-wrapper">' . $table_markup . '<!--Do not remove me--></div>';
  return $form;
}

function avtrans_transaction_list_filter_form($form, &$form_state, $settings = array()) {
  $fields = array(
    '#theme' => 'avtrans_transaction_list_filter_form',
    '#tree' => TRUE,
    '#type' => 'container',
    '#attributes' => array(
      'id' => 'avtrans-transaction-list-filter-form',
    ),
    '#attached' => array(
      'js' => array(AVTRANS_MODULE_PATH . '/js/transaction_list_filter.form.js'),
    ),
  );

  $fields['avtrans.id'] = empty($settings['avtrans.id']) ? array() : $settings['avtrans.id'];
  $fields['avtrans.id'] += array(
    '#type' => 'textfield',
    '#attributes' => array(
      'class' => array('trigger-ajax-search trigger-search-on-keyup'),
      'placeholder' => 'transaction #',
    ),
    '#icon_key' => 'search',
    '#access' => empty($settings['hide'][''])
  );
  $fields['search_text'] = empty($settings['search_text']) ? array() : $settings['search_text'];
  $fields['search_text'] += array(
    '#type' => 'textfield',
    '#attributes' => array(
      'class' => array('trigger-ajax-search trigger-search-on-keyup'),
      'placeholder' => 'search',
    ),
    '#icon_key' => 'search',
  );

  $fields['avcat_agent.title'] = empty($settings['avcat_agent.title']) ? array() : $settings['avcat_agent.title'];
  $fields['avcat_agent.title'] += array(
    '#type' => 'textfield',
    '#title' => t('Agent'),
    '#title_display' => 'none',
    '#maxlength' => 255,
    '#autocomplete_path' => 'av/categories/agent_cust/autocomplete',
    //'#element_validate' => array('avbase_element_validate_category_exists'),
    //'#element_validate_conditions' => array('group_id' => 'agent_cust'),
    '#attributes' => array(
      'placeholder' => 'filter by agent',
      'class' => array('trigger-ajax-search'),
    ),
    //'#element_save_id' => 'agent_id',
    //'#default_value' => empty($row->agent_name) ? '' : $row->agent_name,
    '#access' => FALSE,
  );



  //$date_format = 'M. d, Y';
  $fields['avtrans.transaction_date'] = empty($settings['avtrans.transaction_date']) ? array() : $settings['avtrans.transaction_date'];
  $fields['avtrans.transaction_date'] += array(
    '#type' => 'textfield',
    //'#default_value' => !empty($row->expiry_date) ? format_date($row->expiry_date, 'custom', $date_format) : '',
    //'#element_validate' => array('avbase_element_validate_date'),
    //'#av_date_format' => $date_format,
    '#icon_key' => 'calendar',
    '#attributes' => array(
      'data-uk-datepicker' => "{format:'MMMM DD, YYYY'}",
      'class' => array('trigger-ajax-search'),
      'readonly' => 'readonly',
    ),
  );

  // Set fields' resistance to reset button.
  //foreach ($fields as $k => $v) {
  //
  //}

  // Buttons.
  $fields['buttons']['reset_button'] = empty($settings['reset_button']) ? array() : $settings['reset_button'];
  $fields['buttons']['reset_button'] += array(
    '#id' => 'transaction-reset-btn',
    '#type' => 'submit',
    '#value' => t('reset'),
    //'#button_label' => '<i class="uk-icon-remove"></i>',
  );

  $fields['buttons']['search_button'] = empty($settings['search_button']) ? array() : $settings['search_button'];
  $fields['buttons']['search_button'] += array(
    '#id' => 'transaction-search-btn',
    '#type' => 'submit',
    '#value' => t('Search'),
    '#submit' => array('avtrans_transaction_list_filter_form_submit'),
    '#limit_validation_errors' => array(array('avtrans_tl_filter')),
    '#attributes' => array(
      'class' => array('uk-hidden')
    ),
    '#ajax' => array(
      'callback' => 'avtrans_transaction_form_ajax_search',
      'wrapper' => 'transaction-list-table-wrapper',
      'effect' => 'none',
      'event' => 'click',
      'progress' => array(),
    ),
  );

  $form['avtrans_tl_filter'] = $fields;
  return $form;
}

function avtrans_transaction_list_filter_form_submit($form, &$form_state) {
  $form_state['rebuild'] = TRUE;
  $filter_values = empty($form_state['values']['avtrans_tl_filter']) ? array() : $form_state['values']['avtrans_tl_filter'];
  $arg_index = 0;
  $where = $args = array();
  foreach ($filter_values as $k => $v) {
    if ($k == 'buttons') {
      continue;
    }
    $v = trim($v);
    $arg_name = 'arg_' . $arg_index++;
    if ($k == 'search_text' && $v != '') {
      $or = array();
      $or[] = "avcat_agent.title LIKE :$arg_name";
      $or[] = "avclient.display_name LIKE :$arg_name";
      $where[] = '(' . implode(' OR ', $or) . ')';
      $args[":$arg_name"] = '%' . db_like($v) . '%';
      continue;
    }
    elseif ($k == 'avtrans.transaction_date' && $v != '') {
      $timestamp = strtotime($v);
      if (empty($timestamp)) {
        continue;
      }
      $next_day_timestamp = strtotime('+1 day', $timestamp);
      $where[] = 'avtrans.transaction_date > :stamp1 AND avtrans.transaction_date < :stamp2';
      $args[':stamp1'] = $timestamp;
      $args[':stamp2'] = $next_day_timestamp;
      continue;
    }

    if ($v != '') {
      $where[] = "{$k} = :$arg_name";
      $args[":$arg_name"] = $v;
    }
  }

  $form_state['values']['avtrans_tl_filter']['filter_query'] = array('where' => $where, 'args' => $args);
}


function avtrans_transaction_form_ajax_search($form, $form_state) {
  $trigger = $form_state['triggering_element'];


  switch ($trigger['#id']) {
    case 'transaction-search-btn':
      $target_table_parents = $trigger['#array_parents'];
      $depth = count($target_table_parents) - 4;
      if ($depth > 0) {
        $target_table_parents = array_slice($target_table_parents, 0, $depth);
      }
      else {
        $target_table_parents = empty($trigger['#table_parents']) ? array() : $trigger['#table_parents'];
      }
      $target_table_parents[] = 'transaction_list_table';
      $transaction_list_form = drupal_array_get_nested_value($form, $target_table_parents);
      //dpm($form);
      //dpm($target_table_parents);
      //dpm($transaction_list_form);
      //return $form;
      return $transaction_list_form;
      break;
  }

  return $form;
}