<?php

/**
 * @file
 * AV Products module.
 */

// Constants.
define('AVREPORTS_MODULE_PATH', drupal_get_path('module', 'avreports'));

// Includes.
module_load_include('inc', 'avreports', 'inc/helpers');

// Permissions
define('AVREPORTS_PERM_SOA', 'avbase reports soa');
define('AVREPORTS_PERM_GENERAL', 'avbase reports general');

/**
 * Implementation of hook_permission().
 */
function avreports_permission() {
  $permissions = array(
    AVREPORTS_PERM_SOA => array(
      'title' => 'Statement of Account',
    ),
    AVREPORTS_PERM_GENERAL => array(
      'title' => 'Basic reports',
    ),
  );
  return $permissions;
}

/**
 * Implementation of hook_menu().
 */
function avreports_menu() {
  $items['av/reports'] = array(
    'title' => 'Reports',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('avreports_home_form'),
    'access callback' => 'user_is_logged_in',
    'menu_name' => 'av',
    //'expanded' => TRUE,
  );

  $transaction_types = avtxns_txn_types();
  foreach ($transaction_types as $k => $v) {
    $items['av/reports/transaction-list/' . $k] = array(
      'title' => $v['name'] . ' List',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('avreports_txn_list_form', $k),
      'access arguments' => array(AVREPORTS_PERM_GENERAL),
      'type' => MENU_CALLBACK,
      //'menu_name' => 'av',
      //'expanded' => TRUE,
    );
  }

  $items['av/reports/soa'] = array(
    'title' => 'Statement of Account',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('avreports_soa_form'),
    'access arguments' => array(AVREPORTS_PERM_SOA),
    'type' => MENU_CALLBACK,
  );

  $items['av/reports/inventory-ranking/%'] = array(
    'title' => 'Inventory Ranking',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('avreports_inventory_ranking_form', 3),
    'access arguments' => array(AVREPORTS_PERM_GENERAL),
    'type' => MENU_CALLBACK,
  );

  $items['av/reports/sales-to-trade'] = array(
    'title' => 'Sales to Trade',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('avreports_sales_to_trade_form'),
    'access arguments' => array(AVREPORTS_PERM_GENERAL),
    'type' => MENU_CALLBACK,
  );

  $items['av/reports/profit-loss'] = array(
    'title' => 'Profit & Loss',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('avreports_profit_loss_form'),
    'access arguments' => array(AVREPORTS_PERM_GENERAL),
    'type' => MENU_CALLBACK,
    'file' => 'inc/profit_loss.form.inc',
  );

  return $items;
}

/**
 * Implementation of hook_theme().
 *
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 * @return array
 */
function avreports_theme($existing, $type, $theme, $path) {
  $themes = array();

  $template_path = $path . '/templates';

  // FORMS.
  $theme_names = array(
    'avreports_txn_list',
    'avreports_soa',
    'avreports_balance_ages',
    'avreports_inventory_ranking',
  );
  foreach ($theme_names as $theme_name) {
    $themes[$theme_name] = array(
      'render element' => 'form',
      'template' => str_replace('_', '-', $theme_name),
      'path' => $template_path,
    );
  }

  // OTHERS.
  $theme_names = array(
    //'avtrans_po_mail',
    //'avtrans_po_mail_table',
  );
  foreach ($theme_names as $theme_name) {
    $themes[$theme_name] = array(
      'variables' => array(),
      'template' => str_replace('_', '-', $theme_name),
      'path' => $template_path,
    );
  }

  return $themes;
}

/**
 * Reports Home page.
 * @param $form
 * @param $form_state
 * @return array
 */
function avreports_home_form($form, &$form_state) {
  $form['#attributes']['autocomplete'] = 'off';
  $transaction_types = avtxns_txn_types();

  // Transactions.
  $buttons = array();
  foreach ($transaction_types as $k => $type) {
    $buttons[$k . '_list'] = array('#markup' => l($type['name'] . ' List', 'av/reports/transaction-list/' . $k, array('attributes' => array('class' => array('uk-button uk-button-primary uk-margin-small-right uk-margin-small-bottom')))));
  }
  $form['txn_reports'] = array(
    '#type' => 'fieldset',
    '#title' => t('Transaction List'),
  );
  $form['txn_reports'] += $buttons;

  // Inventory.
  $buttons = array();
  $buttons['inventory_ranking_sales'] = array('#markup' => l('Inventory Ranking - Sales', 'av/reports/inventory-ranking/sales', array('attributes' => array('class' => array('uk-button', 'uk-button-primary uk-margin-small-right')))));
  $buttons['inventory_ranking_purchase'] = array('#markup' => l('Inventory Ranking - Purchase', 'av/reports/inventory-ranking/purchase', array('attributes' => array('class' => array('uk-button', 'uk-button-primary uk-margin-small-right')))));
  $form['inventory_reports'] = array(
    '#type' => 'fieldset',
    '#title' => t('Inventory'),
  );
  $form['inventory_reports'] += $buttons;

  // Accounting.
  $buttons = array();
  $buttons['soa'] = array('#markup' => l('Statement of Account', 'av/reports/soa', array('attributes' => array('class' => array('uk-button', 'uk-button-primary uk-margin-small-right')))));
  $buttons['sales_to_trade'] = array('#markup' => l('Sales to Trade', 'av/reports/sales-to-trade', array('attributes' => array('class' => array('uk-button', 'uk-button-primary uk-margin-small-right')))));
  $buttons['profit_loss'] = array('#markup' => l('Profit & Loss', 'av/reports/profit-loss', array('attributes' => array('class' => array('uk-button', 'uk-button-primary uk-margin-small-right')))));
  $form['accounting_reports'] = array(
    '#type' => 'fieldset',
    '#title' => t('Accounting'),
  );
  $form['accounting_reports'] += $buttons;
  return $form;
}

/**
 * Transaction List report.
 * @param $form
 * @param $form_state
 * @param $transaction_type
 *
 * @return array
 * @throws Exception
 */
function avreports_txn_list_form($form, &$form_state, $transaction_type) {
  global $user;
  $user_filter = empty($form_state['values']['avtxns_tl_filter']) ? array() : $form_state['values']['avtxns_tl_filter'];
  $filter_query = empty($user_filter['filter_query']) ? array() : $user_filter['filter_query'];
  $where = empty($filter_query['where']) ? array() : $filter_query['where'];
  $args = empty($filter_query['args']) ? array() : $filter_query['args'];
  $agent_name = empty($user_filter['avcat_agent.title']) ? '' : $user_filter['avcat_agent.title'];

  // Transaction type details.
  $ttd = avtxns_txn_types($transaction_type);

  // Headers.
  $header = array(
    'id' => array('data' => strtoupper($transaction_type) . '#', 'class' => array('uk-text-center')),
    'customer' => array('data' => 'Customer', 'class' => array('')),
    'total' => array('data' => 'Total', 'class' => array('uk-text-right')),
    'terms' => array('data' => 'Terms', 'class' => array('uk-text-center')),
    'agent' => array('data' => 'Agent', 'class' => array('')),
  );
  if (!empty($agent_name)) {
    unset($header['agent']);
  }


  $where[] = "avtxn.transaction_type = '" . $transaction_type . "'";
  $where[] = "avtxn.status IN (" . AVTXNS_TXN_STATUS_CLOSED . ", " . AVTXNS_TXN_STATUS_OPEN . ")";

  // Add today filter.
  $today = format_date(time(), 'custom', 'F d, Y');
  if (empty($user_filter['avtxn.transaction_date'])) {
    $timestamp = strtotime($today);
    $next_day_timestamp = strtotime('+1 day', $timestamp);
    $where[] = "avtxn.transaction_date >= $timestamp AND avtxn.transaction_date < $next_day_timestamp";
  }

  $filter_form_settings = array(
    'avtxn.id' => array('#access' => FALSE),
    'search_text' => array('#access' => FALSE),
    'avtxn.transaction_date' => array('#default_value' => $today, '#access' => TRUE),
    //'reset_button' => array('#access' => FALSE),
    //'search_button' => array('#table_parents' => array('transaction_list_table')),
  );
  if (!empty($ttd['ctd'])) {
    $filter_form_settings['avcat_agent.title'] = array('#access' => TRUE, '#autocomplete_path' => 'av/categories/agent' . $ttd['ctd']['type'] . '/autocomplete');
  }
  $form['transaction_list_filter'] = avtxns_txn_list_filter_form($form, $form_state, $filter_form_settings);


  $select = array();
  $select[] = 'avtxn_detail.ref_txn_type';
  $select[] = "SUM(
    avtxn_detail.qty
    * avtxn_detail.cost
    * (IF(avtxn_detail.discount1, (1 - avtxn_detail.discount1 / 100), 1))
    * (IF(avtxn_detail.discount2, (1 - avtxn_detail.discount2 / 100), 1))
    * (IF(avtxn_detail.discount3, (1 - avtxn_detail.discount3 / 100), 1))
    * (IF(avtxn_detail.discount4, (1 - avtxn_detail.discount4 / 100), 1))
  ) AS grand_total";
  //$select[] = "IF (
  //    avtxn.transaction_type = '" . AVTXNS_TXN_TYPE_PAYMENT . "',
  //    SUM(avtxn_detail.paid_amount),
  //    (SUM(
  //        avtxn_detail.qty
  //        * avtxn_detail.cost
  //        * (IF(avtxn_detail.discount1, (1 - avtxn_detail.discount1 / 100), 1))
  //        * (IF(avtxn_detail.discount2, (1 - avtxn_detail.discount2 / 100), 1))
  //        * (IF(avtxn_detail.discount3, (1 - avtxn_detail.discount3 / 100), 1))
  //        * (IF(avtxn_detail.discount4, (1 - avtxn_detail.discount4 / 100), 1))
  //      )
  //    )
  //  ) AS grand_total";
  $joins = array();
  $joins[] = 'LEFT JOIN {avtbl_transaction_details} AS avtxn_detail ON avtxn_detail.transaction_id = avtxn.id';
  $group_by = array('avtxn.id', 'avtxn_detail.ref_txn_type');
  $transactions = avtxns_txns_query_load($where, $args, NULL, NULL, NULL, $select, $joins, $group_by);
  $total_receivables = 0;
  $row_totals = array();
  foreach ($transactions as $row) {
    $transaction_type = avtxns_txn_types($row->transaction_type);
    $view_path = "{$transaction_type['base_path']}/$row->id/view";

    if ($transaction_type['type'] == AVTXNS_TXN_TYPE_INVOICE) {
      $row_total = empty($row_totals[$row->id]) ? 0 : $row_totals[$row->id];
      switch ($row->ref_txn_type) {
        case AVTXNS_TXN_TYPE_DELIVERY:
        case AVTXNS_TXN_TYPE_PAYMENT:
          $row_total += $row->grand_total;
          break;
        case AVTXNS_TXN_TYPE_SALES_RETURN:
          $row_total -= $row->grand_total;
          break;
      }
    }
    else {
      $row_total = $row->grand_total;
    }
    $row_totals[$row->id] = $row_total;
    $data = array(
      'id' => array('data' => l($row->id, $view_path), 'class' => array('uk-text-center')),
      'customer' => check_plain($row->display_name),
      'total' => array('data' => l(number_format($row_total, 2), $view_path), 'class' => array('uk-text-right')),
      'terms' => array('data' => check_plain($row->term_name), 'class' => array('uk-text-center')),
      'agent' => array('data' => check_plain($row->agent_name), 'class' => array('')),
    );
    if (!empty($agent_name)) {
      unset($data['agent']);
    }
    $rows[$row->id] = array('data' => $data, 'class' => array('uk-table-middle'));
  }

  foreach ($row_totals as $rt) {
    $total_receivables += $rt;
  }

  if (empty($rows)) {
    $table_markup = '<div class="uk-margin-top uk-text-muted">No match found.</div>';
  }
  else {
    $table_attributes = array(
      'id' => 'transaction-list-table',
      'class' => array('uk-table-condensed uk-table-striped'),
    );
    // Add summary rows at the bottom of the table.
    $rows[] = array('data' => array(array('data' => '&nbsp;', 'colspan' => 10)));
    $rows[] = array(
      'data' => array(
        array('data' => number_format($total_receivables, 2), 'class' => array('uk-text-right'), 'colspan' => 3),
        array('data' => '', 'colspan' => 2),
      ),
      'class' => array('uk-table-middle'),
    );
    $rows[] = array('data' => array(array('data' => '- End of list -', 'colspan' => 10, 'class' => array('uk-text-muted uk-text-center'))));
    $table_markup = theme('table', array('header' => $header, 'rows' => $rows, 'attributes' => $table_attributes));
  }
  //$form['table']['#markup'] = $table_markup;

  $form['transaction_list_table'] = array(
    '#type' => 'container',
    '#theme' => 'avreports_txn_list',
    '#attributes' => array(
      'id' => 'transaction-list-table-wrapper',
      'class' => array('printable')
    ),
  );
  $transaction_list_table['table']['#markup'] = '<!--Do not remove me-->' . $table_markup;
  if (!empty($rows)) {
    $transaction_list_table['transaction_date'] = array(
      '#title' => 'Transaction Date',
      '#title_display' => 'none',
      '#type' => 'item',
      '#markup' => $today,
    );
    $transaction_list_table['agent'] = array(
      '#title' => 'Agent',
      '#title_display' => 'inline-before',
      '#type' => 'item',
      '#markup' => check_plain($agent_name),
      '#access' => !empty($agent_name),
    );
    avbase_user_extra_details($user);
    $transaction_list_table['prepared_by'] = array(
      '#title' => 'Prepared by',
      '#title_display' => 'inline-before',
      '#type' => 'item',
      '#markup' => check_plain($user->avdata->full_name),
    );
    $transaction_list_table['delivered_by'] = array(
      '#title' => 'Delivered by',
      '#title_display' => 'inline-before',
      '#type' => 'item',
      '#markup' => '_______________________________',
      //'#access' => $transaction_type == AVTXNS_TXN_TYPE_DELIVERY,
    );
  }

  $form['transaction_list_table'] += $transaction_list_table;
  //$delivery_report

  //$form['delivery_list_printable'] += $delivery_report;


  $form['buttons']['#theme'] = 'avbase_crud_button_group';
  $form['buttons']['print'] = array(
    '#id' => 'av-print-btn',
    '#type' => 'button',
    '#value' => t('Print...'),
    '#visible_in_view_mode' => TRUE,
    '#attributes' => array('class' => array('uk-button-primary')),
  );

  return $form;
}

/**
 * SOA report.
 * @param $form
 * @param $form_state
 *
 * @return array
 * @throws Exception
 */
function avreports_soa_form($form, &$form_state) {
  global $user;
  $user_filter = empty($form_state['values']['avtxns_tl_filter']) ? array() : $form_state['values']['avtxns_tl_filter'];
  $filter_query = empty($user_filter['filter_query']) ? array() : $user_filter['filter_query'];
  $where = empty($filter_query['where']) ? array() : $filter_query['where'];
  $args = empty($filter_query['args']) ? array() : $filter_query['args'];

  // Headers.
  $header = array(
    'date' => array('data' => 'Date', 'class' => array(''), 'style' => 'width: 13%;'),
    'reference' => array('data' => 'Reference', 'class' => array(''), 'style' => 'width: 12%;'),
    'description' => array('data' => 'Description', 'class' => array(''), 'style' => 'width: 15%;'),
    'debit' => array('data' => 'Debit', 'class' => array('uk-text-right'), 'style' => 'width: 20%;'),
    'credit' => array('data' => 'Credit', 'class' => array('uk-text-right'), 'style' => 'width: 20%;'),
    'balance' => array('data' => 'Balance', 'class' => array('uk-text-right'), 'style' => 'width: 20%;'),
  );

  $where[] = 'avtxn.transaction_type IN (:transaction_types)';
  $args[':transaction_types'] = array(AVTXNS_TXN_TYPE_INVOICE, AVTXNS_TXN_TYPE_PAYMENT, AVTXNS_TXN_TYPE_CUSTOMER_CHARGES);
  $where[] = "avtxn.status IN (" . AVTXNS_TXN_STATUS_CLOSED . ", " . AVTXNS_TXN_STATUS_OPEN . ")";

  // Add today filter.
  $today = format_date(time(), 'custom', 'F d, Y');
  $client_statuses = array(AVCLIENT_STATUS_ACTIVE, AVCLIENT_STATUS_SUSPENDED);
  $filter_form_settings = array(
    'avtxn.id' => array('#access' => FALSE),
    'search_text' => array('#access' => FALSE),
    'avtxn.transaction_date' => array('#access' => FALSE),
    'date_to' => array('#default_value' => $today, '#access' => TRUE),
    'avclients.display_name' => array(
      '#autocomplete_path' => 'av/clients/autocomplete/' . AVCLIENT_TYPE_CUSTOMER . '/' . implode('-', $client_statuses),
      '#attributes' => array(
        'placeholder' => 'search customer',
        'class' => array('trigger-ajax-search'),
      ),
      '#access' => TRUE,
    ),
    //'reset_button' => array('#access' => FALSE),
    //'search_button' => array('#table_parents' => array('transaction_list_table')),
  );
  $form['transaction_list_filter'] = avtxns_txn_list_filter_form($form, $form_state, $filter_form_settings);

  $client_name = empty($user_filter['avclients.display_name']) ? '' : $user_filter['avclients.display_name'];
  $client = NULL;
  if (!empty($client_name)) {
    $client = avclient_query_load(array('avclients.display_name = :name'), array(':name' => $client_name));
    $client = array_shift($client);
  }

  //$select[] = 'avtxn.amount_to_credit';
  $select[] = 'avtxn_detail.ref_txn_type';
  $select[] = avtxns_txn_detail_sum_query_discount_applied() . " AS grand_total";
  //$select[] = "IF (
  //    (avtxn.transaction_type = '" . AVTXNS_TXN_TYPE_PAYMENT . "' OR avtxn.transaction_type = '" . AVTXNS_TXN_TYPE_CUSTOMER_CHARGES . "'),
  //    SUM(avtxn_detail.paid_amount),
  //    (SUM(
  //        avtxn_detail.qty
  //        * avtxn_detail.cost
  //        * (IF(avtxn_detail.discount1, (1 - avtxn_detail.discount1 / 100), 1))
  //        * (IF(avtxn_detail.discount2, (1 - avtxn_detail.discount2 / 100), 1))
  //        * (IF(avtxn_detail.discount3, (1 - avtxn_detail.discount3 / 100), 1))
  //        * (IF(avtxn_detail.discount4, (1 - avtxn_detail.discount4 / 100), 1))
  //      )
  //    )
  //  ) AS grand_total";
  $joins = array();
  $joins[] = 'LEFT JOIN {avtbl_transaction_details} AS avtxn_detail ON avtxn_detail.transaction_id = avtxn.id';
  $group_by = array('avtxn.id', 'avtxn_detail.ref_txn_type');
  $order_by = array('avtxn.transaction_date ASC', 'avtxn_detail.id ASC', 'avtxn.id ASC', 'avtxn_detail.ref_txn_type ASC');
  $transactions = empty($client->id) ? array() : avtxns_txns_query_load($where, $args, NULL, NULL, $order_by, $select, $joins, $group_by);
  $rows = array();
  $total_receivables = 0;
  $balance = 0;

  $opening_balance = isset($client->opening_balance) ? (float) $client->opening_balance : 0;
  if (!empty($opening_balance)) {
    $opening_balance_details = array(
      'transaction_date' => $client->created,
      'grand_total' => $opening_balance,
      'description' => t('Opening balance'),
    );
    array_unshift($transactions, (object) $opening_balance_details);
  }

  foreach ($transactions as $row) {
    //if (isset($row->ref_txn_type) && $row->ref_txn_type == AVTXNS_TXN_TYPE_PAYMENT) {
    //  continue;
    //}
    $date_string = format_date($row->transaction_date, 'custom', 'M. d, Y');
    if (!empty($row->id)) {
      // Get transaction type details.
      $ttd = avtxns_txn_types($row->transaction_type);
      $view_path = "{$ttd['base_path']}/$row->id/view";
      $reference = l(strtoupper($row->transaction_type) . '# ' . $row->id, $view_path);

      // Get reference transaction type details.
      if (!empty($row->ref_txn_type)) {
        $rttd = avtxns_txn_types($row->ref_txn_type);
      }

      switch ($row->ref_txn_type) {
        case AVTXNS_TXN_TYPE_DELIVERY:
          $description = t('Sales');
          break;
        case AVTXNS_TXN_TYPE_SALES_RETURN:
          $description = t('Returns');
          break;
        case AVTXNS_TXN_TYPE_PAYMENT:
          $description = t('Payment credit');
          break;
        case AVTXNS_TXN_TYPE_CREDIT_MEMO:
          $description = t('Credit memo');
          break;
        default:
          $description = $ttd['name'];
          break;
      }
      $description = l($description, $view_path);
      $date_string = l($date_string, $view_path);
    }
    else {
      $reference = empty($row->reference) ? '' : $row->reference;
      $description = empty($row->description) ? '' : $row->description;
    }
    $data = array(
      'date' => array('data' => $date_string, 'class' => array('')),
      'reference' => $reference,
      'description' => array('data' => $description, 'class' => array('')),
      'debit' => array('data' => '', 'class' => array('uk-text-right')),
      'credit' => array('data' => '', 'class' => array('uk-text-right')),
      'balance' => array('data' => '', 'class' => array('uk-text-right')),
    );

    $amount = $row->grand_total;
    //if (empty($ttd['payment'])) {
    //  $amount = $row->grand_total;
    //}
    //else {
    //  $amount = $row->grand_total + (float)$row->amount_to_credit;
    //}

    if (!empty($row->ref_txn_type)) {
      $credit = $rttd['ref_ar_type'] == 'credit' ? $amount : 0;
      $debit = $rttd['ref_ar_type'] == 'debit' ? $amount : 0;
    }
    else {
      $credit = 0;
      $debit = $amount;
    }

    $data['credit']['data'] = empty($credit) ? '' : number_format($credit, 2);
    $data['debit']['data'] = empty($debit) ? '' : number_format($debit, 2);
    $balance = $balance - $credit + $debit;
    $data['balance']['data'] = number_format(round($balance, 2), 2);

    $rows[] = array('data' => $data, 'class' => array('uk-table-middle'));
    $total_receivables += 0;
  }
  if (empty($rows)) {
    $table_markup = '<div class="uk-margin-top uk-text-muted">No match found.</div>';
  }
  else {
    $table_attributes = array(
      'id' => 'transaction-list-table',
      'class' => array('uk-table-condensed uk-table-striped'),
    );
    // Add summary rows at the bottom of the table.
    $rows[] = array('data' => array(array('data' => '&nbsp;', 'colspan' => 10)));
    $rows[] = array(
      'data' => array(
        array('data' => number_format(round($balance, 2), 2), 'class' => array('uk-text-right uk-text-large'), 'colspan' => 13),
      ),
      'class' => array('uk-table-middle'),
    );
    //$rows[] = array('data' => array(array('data' => '- End of list -', 'colspan' => 10, 'class' => array('uk-text-muted uk-text-center'))));
    $table_markup = theme('table', array('header' => $header, 'rows' => $rows, 'attributes' => $table_attributes));
  }
  $form['transaction_list_table'] = array(
    '#type' => 'container',
    '#theme' => 'avreports_soa',
    '#attributes' => array(
      'id' => 'transaction-list-table-wrapper',
      'class' => array('printable')
    ),
  );
  $transaction_list_table['table']['#markup'] = '<!--Do not remove me-->' . $table_markup;
  if (!empty($rows)) {
    $transaction_list_table['date_to'] = array(
      '#title' => 'As of date',
      '#title_display' => 'inline-before',
      '#type' => 'item',
      '#markup' => empty($user_filter['date_to']) ? '' : $user_filter['date_to'],
    );
    avbase_user_extra_details($user);
    $transaction_list_table['prepared_by'] = array(
      '#title' => 'Prepared by',
      '#title_display' => 'inline-before',
      '#type' => 'item',
      '#markup' => check_plain($user->avdata->full_name),
    );
    $transaction_list_table['received_by'] = array(
      '#type' => 'item',
      '#title' => 'Received by',
      '#title_display' => 'inline-before',
      '#markup' => '_______________________________',
      //'#maxlength' => 65000,
    );
    $transaction_list_table['client_name'] = array(
      '#title' => 'Customer',
      '#title_display' => 'none',
      '#type' => 'item',
      '#markup' => check_plain($client->display_name),
    );
    $transaction_list_table['term_name'] = array(
      '#title' => 'Terms',
      '#title_display' => 'inline-before',
      '#type' => 'item',
      '#markup' => check_plain($client->term_name),
    );
    $address = array(
      check_plain($client->address),
      check_plain($client->city) . ' ' . check_plain($client->province),
      check_plain($client->zip_code),
    );
    $transaction_list_table['address'] = array(
      '#title' => 'Address',
      '#title_display' => 'none',
      '#type' => 'item',
      '#markup' => implode('<br />', $address),
    );
    $transaction_list_table['phone'] = array(
      '#title' => 'Contact #',
      '#title_display' => 'inline-before',
      '#type' => 'item',
      '#markup' => empty($client->contact_number) ? '' : check_plain($client->contact_number),
    );
  }

  // Show balance aging.


  if (!empty($client->id)) {
    $transaction_list_table['balance_ages'] = avreports_client_balance_aging_form($client->id);
  }

  $form['transaction_list_table'] += $transaction_list_table;

  $form['buttons']['#theme'] = 'avbase_crud_button_group';
  $form['buttons']['print'] = array(
    '#id' => 'av-print-btn',
    '#type' => 'button',
    '#value' => t('Print...'),
    '#visible_in_view_mode' => TRUE,
    '#attributes' => array('class' => array('')),
    '#icon_key' => 'print',
  );

  return $form;
}

function avreports_inventory_ranking_form($form, &$form_state, $transaction_kind) {
  drupal_set_title('Inventory Ranking - ' . ucfirst($transaction_kind));

  $select = $joins = $where = $args = array();
  $user_filter = empty($form_state['values']['avtxns_tl_filter']) ? array() : $form_state['values']['avtxns_tl_filter'];
  $filter_query = empty($user_filter['filter_query']) ? array() : $user_filter['filter_query'];
  $where = empty($filter_query['where']) ? array() : $filter_query['where'];
  $args = empty($filter_query['args']) ? array() : $filter_query['args'];
  $ctd = array();
  $header = array(
    'placeholder' => array('data' => '', 'class' => array('suk-hidden')),
    'item_name' => array('data' => 'Product', 'field' => 'avproducts.title'),
    'onhand_qty' => array('data' => 'Available Qty.', 'field' => 'avproducts.qty'),
  );
  $select[] = 'avproducts.id';
  $select[] = 'avproducts.title';
  $select[] = 'avproducts.qty';
  $joins[] = 'INNER JOIN {avtbl_transaction_details} AS avtxn_detail ON avtxn_detail.item_id = avproducts.id';
  $joins[] = 'INNER JOIN {avtbl_transactions} AS avtxn ON avtxn.id = avtxn_detail.transaction_id';
  $joins[] = 'LEFT JOIN {avtbl_clients} AS avclients ON avclients.id = avtxn.client_id';
  $joins[] = 'LEFT JOIN {avtbl_categories} AS avcat_agent ON avcat_agent.id = avtxn.agent_id';
  $joins[] = 'LEFT JOIN {avtbl_categories} AS avcat_principal ON avcat_principal.id = avproducts.principal_id';
  $where[] = "avtxn.status IN (" . AVTXNS_TXN_STATUS_CLOSED . ", " . AVTXNS_TXN_STATUS_OPEN . ")";
  if ($transaction_kind == 'purchase') {
    $ctd = avclients_client_types(AVCLIENT_TYPE_VENDOR);
    $header['qty_purchased'] = array('data' => 'Purchased', 'field' => 'qty_purchased', 'class' => array('uk-text-right'));
    $header['total_cost'] = array('data' => 'Total Purchase Cost', 'field' => 'total_cost', 'class' => array('uk-text-right'));
    $select[] = 'SUM(avtxn_detail.qty * avtxn_detail.qty_per_uom) AS qty_purchased';
    $select[] = 'SUM(
      avtxn_detail.qty
      * avtxn_detail.cost
      * (IF(avtxn_detail.discount1, (1 - avtxn_detail.discount1 / 100), 1))
      * (IF(avtxn_detail.discount2, (1 - avtxn_detail.discount2 / 100), 1))
      * (IF(avtxn_detail.discount3, (1 - avtxn_detail.discount3 / 100), 1))
      * (IF(avtxn_detail.discount4, (1 - avtxn_detail.discount4 / 100), 1))
    ) AS total_cost';
    $where[] = "avtxn.transaction_type = :txn_type_bill";
    $args[':txn_type_bill'] = AVTXNS_TXN_TYPE_BILL;
    if (empty($_GET['order'])) {
      $_GET['order'] = 'Total Purchase Cost';
      $_GET['sort'] = 'desc';
    }
  }
  elseif ($transaction_kind == 'sales') {
    $ctd = avclients_client_types(AVCLIENT_TYPE_CUSTOMER);
    $header['qty_sold'] = array('data' => 'Sold', 'field' => 'qty_sold', 'class' => array('uk-text-right'));
    $header['total_sales'] = array('data' => 'Total Sales', 'field' => 'total_sales', 'class' => array('uk-text-right'));
    $select[] = 'SUM(avtxn_detail.qty * avtxn_detail.qty_per_uom) AS qty_sold';
    $select[] = 'SUM(
      avtxn_detail.qty
      * avtxn_detail.cost
      * (IF(avtxn_detail.discount1, (1 - avtxn_detail.discount1 / 100), 1))
      * (IF(avtxn_detail.discount2, (1 - avtxn_detail.discount2 / 100), 1))
      * (IF(avtxn_detail.discount3, (1 - avtxn_detail.discount3 / 100), 1))
      * (IF(avtxn_detail.discount4, (1 - avtxn_detail.discount4 / 100), 1))
    ) AS total_sales';
    $where[] = "avtxn.transaction_type = :txn_type_invoice";
    $where[] = "avtxn_detail.ref_txn_type = :txn_type_delivery";
    $args[':txn_type_invoice'] = AVTXNS_TXN_TYPE_INVOICE;
    $args[':txn_type_delivery'] = AVTXNS_TXN_TYPE_DELIVERY;
    $joins[] = 'LEFT JOIN {avtbl_categories} AS avcat_area ON avcat_area.id = avclients.area_id';
    if (empty($_GET['order'])) {
      $_GET['order'] = 'Total Sales';
      $_GET['sort'] = 'desc';
    }
  }

  // @todo Apply default date from and date to on transactions.
  // Add today filter.
  //if (empty($user_filter['date_to'])) {
  //  $today = format_date(time(), 'custom', 'F d, Y');
  //  $today_timestamp = strtotime($today);
  //  $where[] = "avtxn.transaction_date >= $timestamp AND avtxn.transaction_date < $next_day_timestamp";
  //}

  $client_statuses = array(AVCLIENT_STATUS_ACTIVE, AVCLIENT_STATUS_SUSPENDED);
  $filter_form_settings = array(
    'date_from' => array(
      '#title' => t('Date from'),
      //'#default_value' => $today,
      '#access' => TRUE,
    ),
    'date_to' => array(
      '#title' => t('Date to'),
      //'#default_value' => $today,
      '#access' => TRUE,
    ),
    'avclients.display_name' => array(
      '#title' => $ctd['name'],
      '#autocomplete_path' => 'av/clients/autocomplete/' . $ctd['type'] . '/' . implode('-', $client_statuses),
      '#access' => TRUE,
    ),
    'avcat_agent.title' => array(
      '#title' => t('Agent'),
      '#access' => TRUE,
      '#autocomplete_path' => 'av/categories/agent' . $ctd['type'] . '/autocomplete',
    ),
    'avcat_principal.title' => array(
      '#title' => t('Principal'),
      '#access' => TRUE,
      '#autocomplete_path' => 'av/categories/principal/autocomplete',
    ),
    'avcat_area.title' => array('#access' => $transaction_kind == 'sales'),
    'reset_button' => array('#attributes' => array('style' => 'margin-top: 25px;')),
  );
  $form['transaction_list_filter'] = avtxns_txn_list_filter_form($form, $form_state, $filter_form_settings);
  $form['#transaction_query_exceptions'] = array(
    //'date_to' => array(
    //  '#query_field_aliases' => array('avtxn_purchase.transaction_date', 'avtxn_sales.transaction_date')
    //),
    //'date_from' => array(
    //  '#query_field_aliases' => array('avtxn_purchase.transaction_date', 'avtxn_sales.transaction_date')
    //),
    //'avclients.display_name' => array(
    //  '#query_field_aliases' => array('avclients_vendor.display_name', 'avclients_customer.display_name')
    //),
  );
  // Set table pagination and sort settings.
  if (!empty($user_filter['settings']['table_href'])) {
    $table_ajax_href = $user_filter['settings']['table_href'];
    $href_parts = parse_url($table_ajax_href);
    if (!empty($href_parts['query'])) {
      parse_str($href_parts['query'], $href_query);
      foreach ($href_query as $k => $v) {
        $_GET[$k] = $v;
      }
    }
  }

  $order_by = avbase_build_header_order_array($header);
  $group_by = array();
  $group_by = array('avproducts.id');
  $records = avtxns_product_query_load($where, $args, NULL, NULL, $order_by, $select, $joins, $group_by);
  $rows = array();
  $index = 0;
  $total1 = $total2 = 0;
  foreach ($records as $row) {
    $rows[$index] = array(
      'data' => array(
        'placeholder' => array('data' => $index + 1, 'class' => array('suk-hidden')),
        'item_name' => check_plain($row->title),
        'onhand_qty' => number_format($row->qty),
      ),
      //'class' => array($row_class),
    );

    if ($transaction_kind == 'purchase') {
      $rows[$index]['data']['qty_purchased'] = array('data' => number_format($row->qty_purchased), 'class' => array('uk-text-right'));
      $rows[$index]['data']['total_cost'] = array('data' => number_format($row->total_cost, 2), 'class' => array('uk-text-right'));
      $total1 += $row->qty_purchased;
      $total2 += $row->total_cost;
    }
    elseif ($transaction_kind == 'sales') {
      $rows[$index]['data']['qty_sold'] = array('data' => number_format($row->qty_sold), 'class' => array('uk-text-right'));
      $rows[$index]['data']['total_sales'] = array('data' => number_format($row->total_sales, 2), 'class' => array('uk-text-right'));
      $total1 += $row->qty_sold;
      $total2 += $row->total_sales;
    }
    $index++;
  }
  $rows['spacer'] = array('data' => array('-' => array('colspan' => 10)));
  $rows['total'] = array(
    'data' => array(
      '-' => array('data' => 'Total', 'colspan' => 4),
      //'total1' => array('data' => number_format($total1), 'class' => array('uk-text-right uk-text-bold')),
      'total2' => array('data' => number_format($total2, 2), 'class' => array('uk-text-right uk-text-bold')),
    ),
    //'class' => array(''),
  );

  $table_attributes = array(
    'id' => 'transaction-list-table',
    'class' => array('uk-table-condensed printable'),
  );

  $pager_html = empty($options['#hide_filter_form']) ? theme('pager', array('tags' => array())) : '';
  $table = array(
    '#theme' => 'table',
    '#header' => $header,
    '#rows' => $rows,
    '#empty' => '<div class="uk-text-muted">' . t('No match found.') . '</div>',
    '#attributes' => $table_attributes,
    //'#prefix' => '<div id="transaction-list-table-wrapper">',
    //'#suffix' => $pager_html . '<!--Do not remove me.--></div>',
  );
  $form['transaction_list_table'] = array(
    '#type' => 'container',
    '#theme' => 'avreports_inventory_ranking',
    '#attributes' => array(
      'id' => 'transaction-list-table-wrapper',
      'class' => array('printable')
    ),
  );
  //$transaction_list_table['table']['#markup'] = '<!--Do not remove me-->' . $table_markup;
  $transaction_list_table['table'] = $table;
  //if (!empty($rows)) {
    $client_name = empty($user_filter['avclients.display_name']) ? '' : $user_filter['avclients.display_name'];
    $client = NULL;
    if (!empty($client_name)) {
      $client = avclient_query_load(array('avclients.display_name = :name'), array(':name' => $client_name));
      $client = array_shift($client);
    }
    $transaction_list_table['date_from'] = array(
      '#title' => 'Date from',
      '#title_display' => 'inline-before',
      '#type' => 'item',
      '#markup' => empty($user_filter['date_from']) ? '' : check_plain($user_filter['date_from']),
      '#access' => !empty($user_filter['date_from']),
    );
    $transaction_list_table['date_to'] = array(
      '#title' => 'Date to',
      '#title_display' => 'inline-before',
      '#type' => 'item',
      '#markup' => empty($user_filter['date_to']) ? '' : check_plain($user_filter['date_to']),
      '#access' => !empty($user_filter['date_to']),
    );
    $transaction_list_table['client_name'] = array(
      '#title' => $ctd['name'],
      '#title_display' => 'none',
      '#type' => 'item',
      '#markup' => empty($client_name) ? '' : check_plain($client_name),
      '#access' =>  !empty($client_name),
    );
    $transaction_list_table['address'] = array(
      '#title' => 'Address',
      '#title_display' => 'none',
      '#type' => 'item',
      '#markup' => isset($client->address_string) ? nl2br($client->address_string) : '',
      '#access' => isset($client->address_string),
    );
    $transaction_list_table['phone'] = array(
      '#title' => 'Contact #',
      '#title_display' => 'inline-before',
      '#type' => 'item',
      '#markup' => empty($client->contact_number) ? '' : check_plain($client->contact_number),
      '#access' => !empty($client->contact_number),
    );
    $transaction_list_table['agent_name'] = array(
      '#title' => 'Agent',
      '#title_display' => 'inline-before',
      '#type' => 'item',
      '#markup' => empty($user_filter['avcat_agent.title']) ? '' : check_plain($user_filter['avcat_agent.title']),
      '#access' =>  !empty($user_filter['avcat_agent.title']),
    );
    $transaction_list_table['principal_name'] = array(
      '#title' => 'Principal',
      '#title_display' => 'inline-before',
      '#type' => 'item',
      '#markup' => empty($user_filter['avcat_principal.title']) ? '' : check_plain($user_filter['avcat_principal.title']),
      '#access' =>  !empty($user_filter['avcat_principal.title']),
    );
    $transaction_list_table['area_name'] = array(
      '#title' => 'Area',
      '#title_display' => 'inline-before',
      '#type' => 'item',
      '#markup' => empty($user_filter['avcat_area.title']) ? '' : check_plain($user_filter['avcat_area.title']),
      '#access' =>  !empty($user_filter['avcat_area.title']),
    );
  //}
  $form['transaction_list_table'] += $transaction_list_table;

  $form['buttons']['#theme'] = 'avbase_crud_button_group';
  $form['buttons']['print'] = array(
    '#id' => 'av-print-btn',
    '#type' => 'button',
    '#value' => t('Print...'),
    '#visible_in_view_mode' => TRUE,
    '#attributes' => array('class' => array('')),
    '#icon_key' => 'print',
  );
  return $form;
}

function avreports_sales_to_trade_form($form, &$form_state) {
  $client_statuses = array(AVCLIENT_STATUS_ACTIVE, AVCLIENT_STATUS_SUSPENDED);
  $ctd = avclients_client_types(AVCLIENT_TYPE_CUSTOMER);
  $dad = avtxns_txn_list_filter_date_auto_options();
  $dad_default = empty($dad['this_week']) ? array() : $dad['this_week'];
  $filter_form_settings = array(
    'date_auto' => array(
      '#title' => t('Dates'),
      '#default_value' => 'this_week',
    ),
    'date_from' => array(
      '#title' => t('Date from'),
      '#default_value' => $dad_default['date_from'],
    ),
    'date_to' => array(
      '#title' => t('Date to'),
      '#default_value' => $dad_default['date_to'],
    ),
    'avclients.display_name' => array(
      '#title' => $ctd['name'],
      '#autocomplete_path' => 'av/clients/autocomplete/' . $ctd['type'] . '/' . implode('-', $client_statuses),
    ),
    'avcat_agent.title' => array(
      '#title' => t('Agent'),
      '#autocomplete_path' => 'av/categories/agent' . $ctd['type'] . '/autocomplete',
    ),
    'avcat_principal.title' => array(
      '#title' => t('Principal'),
      '#autocomplete_path' => 'av/categories/principal/autocomplete',
    ),
    //'avcat_area.title' => array('#access' => $transaction_kind == 'sales'),
    'table_columns' => array(
      '#options' => array(
        'agent_name' => 'Agent',
        'client_name' => 'Customer',
        'client_address' => 'Address',
        'principal_name' => 'Principal',
        'item_name' => 'Product',
      ),
      '#default_value' => array('agent_name'),
    ),
    'table_group_by' => array(
      '#options' => array(
        '' => 'No grouping',
        'agent_name' => 'Agent',
        'client_name' => 'Customer',
        'principal_name' => 'Principal',
      ),
    ),
    'reset_button' => array('#attributes' => array('style' => 'margin-top: 25px;')),
  );
  $form['transaction_list_filter'] = avtxns_txn_list_filter_form($form, $form_state, $filter_form_settings);

  // Prepare query variables.
  $select = $joins = $where = $args = array();
  $user_filter = empty($form_state['values']['avtxns_tl_filter']) ? array() : $form_state['values']['avtxns_tl_filter'];
  $filter_query = empty($user_filter['filter_query']) ? array() : $user_filter['filter_query'];
  $where = empty($filter_query['where']) ? array() : $filter_query['where'];
  $args = empty($filter_query['args']) ? array() : $filter_query['args'];

  // Headers.
  $header = array(
    'agent_name' => array('data' => 'Agent', 'field' => 'agent_name'),
    'client_name' => array('data' => 'Customer', 'field' => 'client_name'),
    'client_address' => array('data' => 'Address'),
    'principal_name' => array('data' => 'Principal', 'field' => 'principal_name'),
    'item_name' => array('data' => 'Product', 'field' => 'avproducts.title'),
    //'onhand_qty' => array('data' => 'Available Qty.', 'field' => 'avproducts.qty'),
  );
  $table_columns = empty($user_filter['settings']['table_columns']) ? array() : $user_filter['settings']['table_columns'];
  $table_columns = array_filter($table_columns);
  foreach ($header as $h_k => $h) {
    if (!isset($table_columns[$h_k])) {
      unset($header[$h_k]);
    }
  }
  $header['total_sales'] = array('data' => 'Sales', 'field' => 'total_sales', 'class' => array('uk-text-right'));

  // Build query.
  // Add default date from and date to.
  //if (empty($user_filter['date_to'])) {
  //  $today = format_date(time(), 'custom', 'F d, Y');
  //  $today_timestamp = strtotime($today);
  //  $where[] = "avtxn.transaction_date >= $timestamp AND avtxn.transaction_date < $next_day_timestamp";
  //}

  $joins[] = 'INNER JOIN {avtbl_transaction_details} AS avtxn_detail ON avtxn_detail.item_id = avproducts.id';
  $joins[] = 'INNER JOIN {avtbl_transactions} AS avtxn ON avtxn.id = avtxn_detail.transaction_id';
  $where[] = "avtxn.status IN (" . AVTXNS_TXN_STATUS_CLOSED . ", " . AVTXNS_TXN_STATUS_OPEN . ")";
  if (isset($table_columns['agent_name']) || !empty($user_filter['avcat_agent.title'])) {
    $select[] = 'avcat_agent.title AS agent_name';
    $joins[] = 'LEFT JOIN {avtbl_categories} AS avcat_agent ON avcat_agent.id = avtxn.agent_id';
  }
  if (isset($table_columns['client_name']) || !empty($user_filter['avclients.display_name'])) {
    $select[] = 'avclients.display_name AS client_name';
    $joins['clients'] = 'LEFT JOIN {avtbl_clients} AS avclients ON avclients.id = avtxn.client_id';
  }
  if (isset($table_columns['client_address'])) {
    $select[] = 'avclients.address';
    $select[] = 'avclients.province';
    $select[] = 'avclients.city';
    $select[] = 'avclients.zip_code';
    $joins['clients'] = 'LEFT JOIN {avtbl_clients} AS avclients ON avclients.id = avtxn.client_id';
  }
  if (isset($table_columns['principal_name']) || !empty($user_filter['avcat_principal.title'])) {
    $select[] = 'avcat_principal.title AS principal_name';
    $joins[] = 'LEFT JOIN {avtbl_categories} AS avcat_principal ON avcat_principal.id = avproducts.principal_id';
  }
  if (isset($table_columns['item_name'])) {
    $select[] = 'avproducts.title';
  }
  //$joins[] = 'LEFT JOIN {avtbl_categories} AS avcat_area ON avcat_area.id = avclients.area_id';

  $select[] = avtxns_txn_detail_sum_query_discount_applied() . ' AS total_sales';
  $where[] = "avtxn.transaction_type = :txn_type_invoice";
  $where[] = "avtxn_detail.ref_txn_type = :txn_type_delivery";
  $args[':txn_type_invoice'] = AVTXNS_TXN_TYPE_INVOICE;
  $args[':txn_type_delivery'] = AVTXNS_TXN_TYPE_DELIVERY;

  if (empty($_GET['order'])) {
    $_GET['order'] = 'Total Sales';
    $_GET['sort'] = 'desc';
  }






  // Set table pagination and sort settings.
  if (!empty($user_filter['settings']['table_href'])) {
    $table_ajax_href = $user_filter['settings']['table_href'];
    $href_parts = parse_url($table_ajax_href);
    if (!empty($href_parts['query'])) {
      parse_str($href_parts['query'], $href_query);
      foreach ($href_query as $k => $v) {
        $_GET[$k] = $v;
      }
    }
  }
  $order_by = avbase_build_header_order_array($header);
  $group_by = array();
  $group_by = array(
    'agent_name' => 'avtxn.agent_id',
    'client_name' => 'avtxn.client_id',
    'principal_name' => 'avproducts.principal_id',
    'item_name' => 'avproducts.id'
  );
  foreach ($group_by as $g_k => $g) {
    if (!isset($table_columns[$g_k])) {
      if ($g_k == 'client_name' && isset($table_columns['client_address'])) {
        continue;
      }
      unset($group_by[$g_k]);
    }
  }
  $records = avtxns_product_query_load($where, $args, NULL, NULL, $order_by, $select, $joins, $group_by);

  // Group result.
  $table_group_by = empty($user_filter['settings']['table_group_by']) ? NULL : $user_filter['settings']['table_group_by'];
  $grouped_records = array();
  foreach ($records as $row) {
    $group_id = isset($row->$table_group_by) ? $row->$table_group_by : '';
    $grouped_records[check_plain($group_id)][] = $row;
  }

  // List result.
  $rows = array();
  $index = 0;
  $total2 = 0;
  foreach ($grouped_records as $group_id => $group) {
    $group_total = 0;
    foreach ($group as $row) {
      $table_row = array(
        'data' => array(
          //'placeholder' => array('data' => $index + 1, 'class' => array('suk-hidden')),
          'agent_name' => isset($table_columns['agent_name']) ? check_plain($row->agent_name) : '',
          'client_name' => isset($table_columns['client_name']) ? check_plain($row->client_name) : '',
          'client_address' => isset($table_columns['client_address']) ? avclients_address_string_format($row) : '',
          'principal_name' => isset($table_columns['principal_name']) ? check_plain($row->principal_name) : '',
          'item_name' => isset($table_columns['item_name']) ? check_plain($row->title) : '',
        ),
        'class' => array('uk-text-uppercase'),
      );

      if (!empty($group_total) && isset($table_row['data'][$table_group_by])) {
        $table_row['data'][$table_group_by] = '';
        if ($table_group_by == 'client_name') {
          $table_row['data']['client_address'] = '';
        }
      }

      foreach ($table_row['data'] as $d_k => $d) {
        if (!isset($table_columns[$d_k])) {
          unset($table_row['data'][$d_k]);
        }
      }
      $table_row['data']['total_sales'] = array('data' => number_format($row->total_sales, 2), 'class' => array('uk-text-right'));

      //$table_row['data']['qty_sold'] = array('data' => number_format($row->qty_sold), 'class' => array('uk-text-right'));
      //$table_row['data']['total_sales'] = array('data' => number_format($row->total_sales, 2), 'class' => array('uk-text-right'));
      $total2 += $row->total_sales;
      $group_total += $row->total_sales;

      $rows[] = $table_row;
      $index++;
    }

    $group_totals_row =  array(
      'data' => array(
        'spacer' => array('data' => $group_id . ' - Total', 'colspan' => 1, 'class' => array(' uk-text-right uk-text-uppercase')),
        'total2' => array('data' => number_format($group_total, 2), 'class' => array('uk-text-right uk-text-bold')),
      ),
      //'class' => array('uk-row-mute'),
    );
    if (empty($table_columns)) {
      unset($group_totals_row['data']['spacer']);
    }
    else {
      $group_totals_row['data']['spacer']['colspan'] = count($table_columns);
    }
    $rows[] = $group_totals_row;
    $rows[] = array('data' => array('-' => array('data' => '&nbsp', 'colspan' => 10)));
    //$rows[] = array('data' => array('-' => array('colspan' => 10)));
  }

  //$rows['spacer'] = array('data' => array('-' => array('colspan' => 10)));
  //$rows['total'] = array(
  //  'data' => array(
  //    'spacer' => array('data' => 'Total', 'colspan' => 1),
  //    //'total1' => array('data' => number_format($total1), 'class' => array('uk-text-right uk-text-bold')),
  //    'total2' => array('data' => number_format($total2, 2), 'class' => array('uk-text-right uk-text-bold')),
  //  ),
  //  //'class' => array(''),
  //);
  //if (empty($table_columns)) {
  //  unset($rows['total']['data']['spacer']);
  //}
  //else {
  //  $rows['total']['data']['spacer']['colspan'] = count($table_columns);
  //}

  $table_attributes = array(
    'id' => 'transaction-list-table',
    'class' => array('uk-table-condensed uk-table-hover sprintable'),
  );

  //$pager_html = empty($options['#hide_filter_form']) ? theme('pager', array('tags' => array())) : '';
  $table = array(
    '#theme' => 'table',
    '#header' => $header,
    '#rows' => $rows,
    '#empty' => '<div class="uk-text-muted">' . t('No match found.') . '</div>',
    '#attributes' => $table_attributes,
  );
  $form['transaction_list_table'] = array(
    '#type' => 'container',
    '#theme' => 'avreports_inventory_ranking',
    '#attributes' => array(
      'id' => 'transaction-list-table-wrapper',
      'class' => array('printable')
    ),
  );
  //$transaction_list_table['table']['#markup'] = '<!--Do not remove me-->' . $table_markup;
  $transaction_list_table['table'] = $table;
  //if (!empty($rows)) {
  $client_name = empty($user_filter['avclients.display_name']) ? '' : $user_filter['avclients.display_name'];
  $client = NULL;
  if (!empty($client_name)) {
    $client = avclient_query_load(array('avclients.display_name = :name'), array(':name' => $client_name));
    $client = array_shift($client);
  }
  $transaction_list_table['date_from'] = array(
    '#title' => 'Date From',
    '#title_display' => 'inline-before',
    '#type' => 'item',
    '#markup' => empty($user_filter['date_from']) ? '' : check_plain($user_filter['date_from']),
    '#access' => !empty($user_filter['date_from']),
  );
  $transaction_list_table['date_to'] = array(
    '#title' => 'Date To',
    '#title_display' => 'inline-before',
    '#type' => 'item',
    '#markup' => empty($user_filter['date_to']) ? '' : check_plain($user_filter['date_to']),
    '#access' => !empty($user_filter['date_to']),
  );
  //$transaction_list_table['client_name'] = array(
  //  '#title' => $ctd['name'],
  //  '#title_display' => 'none',
  //  '#type' => 'item',
  //  '#markup' => empty($client_name) ? '' : check_plain($client_name),
  //  '#access' =>  !empty($client_name),
  //);
  //$transaction_list_table['address'] = array(
  //  '#title' => 'Address',
  //  '#title_display' => 'none',
  //  '#type' => 'item',
  //  '#markup' => isset($client->address_string) ? nl2br($client->address_string) : '',
  //  '#access' => isset($client->address_string),
  //);
  //$transaction_list_table['phone'] = array(
  //  '#title' => 'Contact #',
  //  '#title_display' => 'inline-before',
  //  '#type' => 'item',
  //  '#markup' => empty($client->contact_number) ? '' : check_plain($client->contact_number),
  //  '#access' => !empty($client->contact_number),
  //);
  //$transaction_list_table['agent_name'] = array(
  //  '#title' => 'Agent',
  //  '#title_display' => 'inline-before',
  //  '#type' => 'item',
  //  '#markup' => empty($user_filter['avcat_agent.title']) ? '' : check_plain($user_filter['avcat_agent.title']),
  //  '#access' =>  !empty($user_filter['avcat_agent.title']),
  //);
  //$transaction_list_table['principal_name'] = array(
  //  '#title' => 'Principal',
  //  '#title_display' => 'inline-before',
  //  '#type' => 'item',
  //  '#markup' => empty($user_filter['avcat_principal.title']) ? '' : check_plain($user_filter['avcat_principal.title']),
  //  '#access' =>  !empty($user_filter['avcat_principal.title']),
  //);
  $transaction_list_table['area_name'] = array(
    '#title' => 'Area',
    '#title_display' => 'inline-before',
    '#type' => 'item',
    '#markup' => empty($user_filter['avcat_area.title']) ? '' : check_plain($user_filter['avcat_area.title']),
    '#access' =>  !empty($user_filter['avcat_area.title']),
  );
  //}
  $form['transaction_list_table'] += $transaction_list_table;

  $form['buttons']['#theme'] = 'avbase_crud_button_group';
  $form['buttons']['print'] = array(
    '#id' => 'av-print-btn',
    '#type' => 'button',
    '#value' => t('Print...'),
    '#visible_in_view_mode' => TRUE,
    '#icon_key' => 'print',
  );
  return $form;
}
