<?php

/**
 * @file
 * AV Products module.
 */

// Constants.
define('AVREPORTS_MODULE_PATH', drupal_get_path('module', 'avreports'));

// Includes.
module_load_include('inc', 'avreports', 'inc/helpers');

/**
 * Implementation of hook_menu().
 */
function avreports_menu() {
  $items['av/reports'] = array(
    'title' => 'Reports',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('avreports_home_form'),
    'access callback' => 'user_is_logged_in',
    'menu_name' => 'av',
    'expanded' => TRUE,
  );
  $items['av/reports/delivery-list'] = array(
    'title' => 'Delivery List',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('avreports_delivery_list_form'),
    'access callback' => 'user_is_logged_in',
    'type' => MENU_CALLBACK,
    //'menu_name' => 'av',
    //'expanded' => TRUE,
  );
  return $items;
}

/**
 * Implementation of hook_theme().
 *
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 * @return array
 */
function avreports_theme($existing, $type, $theme, $path) {
  $themes = array();

  $template_path = $path . '/templates';

  // FORMS.
  $theme_names = array(
    'avreports_delivery_list',
  );
  foreach ($theme_names as $theme_name) {
    $themes[$theme_name] = array(
      'render element' => 'form',
      'template' => str_replace('_', '-', $theme_name),
      'path' => $template_path,
    );
  }

  // OTHERS.
  $theme_names = array(
    //'avtrans_po_mail',
    //'avtrans_po_mail_table',
  );
  foreach ($theme_names as $theme_name) {
    $themes[$theme_name] = array(
      'variables' => array(),
      'template' => str_replace('_', '-', $theme_name),
      'path' => $template_path,
    );
  }

  return $themes;
}

/**
 * Reports Home page.
 * @param $form
 * @param $form_state
 * @return array
 */
function avreports_home_form($form, &$form_state) {
// Set autocomplete off.
  $form['#attributes']['autocomplete'] = 'off';

  $form['delivery_list'] = array('#markup' => l('Delivery List', 'av/reports/delivery-list', array('attributes' => array('class' => array('uk-button', 'uk-button-primary')))));
  return $form;
}

/**
 * Delivery List report.
 * @param $form
 * @param $form_state
 *
 * @return array
 * @throws Exception
 */
function avreports_delivery_list_form($form, &$form_state) {
  // Headers.
  $header = array(
    array('data' => 'Order #', 'class' => array('uk-text-center uk-width-1-10')),
    array('data' => 'Customer', 'class' => array('uk-width-3-10')),
    array('data' => 'Receivable', 'class' => array('uk-text-right uk-width-2-10')),
    array('data' => 'Terms', 'class' => array('uk-text-center uk-width-1-10')),
    array('data' => 'Agent', 'class' => array('uk-width-3-10')),
  );


  $user_filter = empty($form_state['values']['avtrans_tl_filter']) ? array() : $form_state['values']['avtrans_tl_filter'];
  $filter_query = empty($user_filter['filter_query']) ? array() : $user_filter['filter_query'];
  $where = empty($filter_query['where']) ? array() : $filter_query['where'];
  $args = empty($filter_query['args']) ? array() : $filter_query['args'];

  $where['transaction_types'] = array('dr');
  $where[] = 'avtrans.status = 1';

  // Add today filter.
  $today = format_date(time(), 'custom', 'F d, Y');
  if (empty($user_filter['avtrans.transaction_date'])) {
    $timestamp = strtotime($today);
    $next_day_timestamp = strtotime('+1 day', $timestamp);
    $where[] = "avtrans.transaction_date > $timestamp AND avtrans.transaction_date < $next_day_timestamp";
  }

  $filter_form_settings = array(
    'avtrans.id' => array('#access' => FALSE),
    'search_text' => array('#access' => FALSE),
    'avtrans.transaction_date' => array('#default_value' => $today),
    'avcat_agent.title' => array('#access' => TRUE),
    //'reset_button' => array('#access' => FALSE),
    //'search_button' => array('#table_parents' => array('transaction_list_table')),
  );
  $form['transaction_list_filter'] = avtrans_transaction_list_filter_form($form, $form_state, $filter_form_settings);



  $transactions = avtrans_transactions_query_load($where, $args);
  $total_receivables = 0;
  foreach ($transactions as $row) {
    $transaction_type = avtrans_transaction_types($row->transaction_type);
    $view_path = "{$transaction_type['base_path']}/$row->transaction_id/view";
    $rows[] = array(
      'data' => array(
        array('data' => l($row->transaction_id, $view_path), 'class' => array('uk-text-center')),
        check_plain($row->display_name),
        array('data' => l(number_format($row->grand_total, 2), $view_path), 'class' => array('uk-text-right')),
        array('data' => check_plain($row->term_name), 'class' => array('uk-text-center')),
        array('data' => check_plain($row->agent_name), 'class' => array('')),
      ),
      'class' => array('uk-table-middle'),
    );
    $total_receivables += $row->grand_total;
  }


  if (empty($rows)) {
    $table_markup = '<div class="uk-margin-top uk-text-muted">No match found.</div>';
  }
  else {
    $table_attributes = array(
      'id' => 'transaction-list-table',
      'class' => array(),
    );
    // Add summary rows at the bottom of the table.
    $rows[] = array('data' => array(array('data' => '&nbsp;', 'colspan' => 10)));
    $rows[] = array(
      'data' => array(
        array('data' => number_format($total_receivables, 2), 'class' => array('uk-text-right'), 'colspan' => 3),
        array('data' => '', 'colspan' => 2),
      ),
      'class' => array('uk-table-middle'),
    );
    $table_markup = theme('table', array('header' => $header, 'rows' => $rows, 'attributes' => $table_attributes));
  }
  //$form['table']['#markup'] = $table_markup;

  $form['transaction_list_table'] = array(
    '#type' => 'container',
    '#theme' => 'avreports_delivery_list',
    '#attributes' => array(
      'id' => 'transaction-list-table-wrapper',
      'class' => array('printable')
    ),
  );
  $transaction_list_table['table']['#markup'] = '<!--Do not remove me-->' . $table_markup;
  if (!empty($rows)) {
    $transaction_list_table['transaction_date'] = array(
      '#title' => 'Transaction Date',
      '#type' => 'item',
      '#markup' => $today,
    );
    $agent_name = empty($user_filter['avcat_agent.title']) ? '' : $user_filter['avcat_agent.title'];
    $transaction_list_table['agent'] = array(
      '#title' => 'Agent',
      '#type' => 'item',
      '#markup' => check_plain($agent_name),
      '#access' => !empty($agent_name),
    );
  }

  $form['transaction_list_table'] += $transaction_list_table;
  //$delivery_report

  //$form['delivery_list_printable'] += $delivery_report;


  $form['buttons']['#theme'] = 'avbase_crud_button_group';
  $form['buttons']['print'] = array(
    '#id' => 'av-print-btn',
    '#type' => 'button',
    '#value' => t('Print...'),
    '#visible_in_view_mode' => TRUE,
    '#attributes' => array('class' => array('uk-button-primary')),
  );

  return $form;
}
