<?php
/**
 * @file
 * UCT base features and functions.
 */

define('AVCATEGORY_ID_PAYMENT_METHOD', 1);
define('AVCATEGORY_ID_PRODUCT_CATEGORY', 2);
define('AVCATEGORY_ID_UNIT_OF_MEASURE', 3);

require_once 'inc/helpers.inc';

/**
 * Implements hook_modules_installed().
 *
 * @see avbase_install()
 */
function avbase_modules_installed($modules) {
  if (in_array('menu', $modules)) {
    $menu = array(
      'menu_name' => 'av',
      'title' => t('AV Menu'),
      'description' => t('AV AIS links'),
    );
    menu_save($menu);
  }
}


/**
 * Implementation of hook_init().
 */
function avbase_init() {

}

/**
 * Implementation of hook_menu().
 */
function avbase_menu() {
  $items = array();
  return $items;
}

/**
 * Implementation of hook_form_alter().
 * @param $form
 * @param $form_state
 * @param $form_id
 */
function avbase_form_alter(&$form, $form_state, $form_id) {
  if (!user_access('administer modules')) {
    if ($form_id == 'user_filter_form') {
      $form['#access'] = FALSE;
    }

    if ($form_id == 'user_admin_account') {
      drupal_set_title('Users');
      $form['options']['#access'] = FALSE;
    }
  }
}