<?php

/**
 * @file
 * AV Dashboard to show system overview.
 */

define('AVDASHBOARD_MODULE_PATH', drupal_get_path('module', 'avdashboard'));

/**
 * Implementation of hook_menu().
 */
function avdashboard_menu() {
  $items['av/dashboard'] = array(
    'title' => 'Dashboard',
    'description' => 'Business and system overview',
    'page callback' => 'avdashboard_home',
    'access arguments' => array('access content'),
    'menu_name' => 'av',
    'expanded' => TRUE,
    'weight' => -1,
  );
  $items['av/grid'] = array(
    'title' => 'Grid',
    'page callback' => 'avdashboard_grid',
    'access arguments' => array('access content'),
    'menu_name' => 'av',
    'expanded' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Home
 */
function avdashboard_home() {
  drupal_add_css(AVDASHBOARD_MODULE_PATH . '/css/avdashboard.css', array('type' => 'external'));
  drupal_add_js(AVDASHBOARD_MODULE_PATH . '/js/amcharts_3.20.17/amcharts/amcharts.js');
  drupal_add_js(AVDASHBOARD_MODULE_PATH . '/js/amcharts_3.20.17/amcharts/serial.js');
  drupal_add_js(AVDASHBOARD_MODULE_PATH . '/js/amcharts_3.20.17/amcharts/themes/light.js');
  drupal_add_js(AVDASHBOARD_MODULE_PATH . '/js/avdashboard.js');
  $output = <<<HTML
<div class="uk-grid">

  <div class="uk-width-1-3">
    <div class="uk-block uk-block-muted">

      <div class="uk-container uk-container-center">

        <h3>The quick brown fox jumped.</h3>

        <div class="uk-grid uk-grid-width-medium-1-1" data-uk-grid-margin="">
          <div class="">
            <div class="uk-panel">
              <p>A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart.</p>
              <p>I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents.</p>
              <!--<p>I should be incapable of drawing a single stroke at the present moment; and yet I feel that I never was a greater artist than now. When, while the lovely valley teems with vapour around me, and the meridian sun strikes the upper surface of the impenetrable foliage of my trees, and but a few stray gleams steal into the inner sanctuary, I throw myself down among the tall grass by the trickling stream; and, as I lie close to the earth, a thousand unknown plants are noticed by me: when I hear the buzz of the little world among the stalks, and grow familiar with the countless indescribable forms of the insects and flies, then I feel the presence of the Almighty, who formed us in his own image, and the breath</p>-->
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>

  <div class="uk-width-2-3">
    <div id="chartdiv" style="height: 500px;"></div>
  </div>
</div>
HTML;

  return $output;
}

/**
 * Home
 */
function avdashboard_customer() {
  return 'Customers!';
}

/**
 * Home
 */
function avdashboard_somepage() {
  return 'Somepage!';
}

/**
 * Home
 */
function avdashboard_somepage2() {
  return 'Somepage 2!';
}

function avdashboard_grid() {
    drupal_add_js('sites/all/libraries/ag-grid/ag-grid.min.js');
  drupal_add_js(AVCUSTOMERS_MODULE_PATH . '/js/avcustomers.js');
  $output = <<<HTML
<div id="myGrid" style="height: 300px;" class="ag-fresh"></div>
<div class="uk-button-group uk-margin-top uk-align-right">
    <button class="uk-button uk-button-primary">Print..</button>
    <button class="uk-button uk-button-danger">Export..</button>
    <button class="uk-button">Save as..</button>
</div>
HTML;

  return $output;
}