<?php

/**
 * @file
 * AV Dashboard to show system overview.
 */

/**
 * Implementation of hook_menu().
 */
function avdashboard_menu() {
  $items['av/dashboard'] = array(
    'title' => 'Dashboard',
    'page callback' => 'avdashboard_home',
    'access arguments' => array('access content'),
    'menu_name' => 'av',
    'expanded' => TRUE,
    'weight' => -1,
  );

  $items['av/products'] = array(
    'title' => 'Products',
    'page callback' => 'avdashboard_somepage2',
    'access arguments' => array('access content'),
    'menu_name' => 'av',
    'expanded' => TRUE,
  );
  return $items;
}

/**
 * Home
 */
function avdashboard_home() {
  $output = <<<HTML
<div class="uk-block uk-block-muted">

                                <div class="uk-container uk-container-center">

                                <h3>The quick brown fox jumps over the lazy dog</h3>

                                    <div class="uk-grid uk-grid-width-medium-1-2" data-uk-grid-margin="">
                                        <div class="">
                                            <div class="uk-panel">
                                                <p>A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents.</p>

<p>I should be incapable of drawing a single stroke at the present moment; and yet I feel that I never was a greater artist than now. When, while the lovely valley teems with vapour around me, and the meridian sun strikes the upper surface of the impenetrable foliage of my trees, and but a few stray gleams steal into the inner sanctuary, I throw myself down among the tall grass by the trickling stream; and, as I lie close to the earth, a thousand unknown plants are noticed by me: when I hear the buzz of the little world among the stalks, and grow familiar with the countless indescribable forms of the insects and flies, then I feel the presence of the Almighty, who formed us in his own image, and the breath</p>
                                            </div>
                                        </div>
                                        <div class="">
                                            <div class="uk-panel">
                                                <p>One morning, when Gregor Samsa woke from troubled dreams, he found himself transformed in his bed into a horrible vermin. He lay on his armour-like back, and if he lifted his head a little he could see his brown belly, slightly domed and divided by arches into stiff sections.</p>

<p>The bedding was hardly able to cover it and seemed ready to slide off any moment. His many legs, pitifully thin compared with the size of the rest of him, waved about helplessly as he looked. "What's happened to me? " he thought. It wasn't a dream. His room, a proper human room although a little too small, lay peacefully between its four familiar walls. A collection of textile samples lay spread out on the table - Samsa was a travelling salesman - and above it there hung a picture that he had recently cut out of an illustrated magazine and housed</p>
                                            </div>
                                        </div>
                                    </div>

                                </div>

                            </div>
HTML;

  return $output;
}

/**
 * Home
 */
function avdashboard_customer() {
  return 'Customers!';
}

/**
 * Home
 */
function avdashboard_somepage() {
  return 'Somepage!';
}

/**
 * Home
 */
function avdashboard_somepage2() {
  return 'Somepage 2!';
}