<?php

module_load_include('inc', 'avtxns', 'inc/helpers');

define('AVTXNS_MODULE_PATH', drupal_get_path('module', 'avtxns'));
define('AVTXNS_RETURN_TYPE_RUD', 1);
define('AVTXNS_RETURN_TYPE_RS', 2);

define('AVTXNS_TXN_TYPE_PURCHASE_ORDER', 'po');
define('AVTXNS_TXN_TYPE_RECEIVE', 'rcv');
define('AVTXNS_TXN_TYPE_PURCHASE_RETURN', 'pr');
define('AVTXNS_TXN_TYPE_CREATE_BILL', 'bll');
define('AVTXNS_TXN_TYPE_PAY_BILL', 'blp');
define('AVTXNS_TXN_TYPE_SALES_ORDER', 'so');
define('AVTXNS_TXN_TYPE_DELIVERY', 'dr');
define('AVTXNS_TXN_TYPE_SALES_RETURN', 'sr');
define('AVTXNS_TXN_TYPE_INVOICE', 'inv');
define('AVTXNS_TXN_TYPE_PAYMENT', 'pmt');

define('AVTXNS_TXN_STATUS_CLOSED', 0);
define('AVTXNS_TXN_STATUS_OPEN', 1);
define('AVTXNS_TXN_STATUS_PENDING', 2);
define('AVTXNS_TXN_STATUS_VOID', 3);

define('AVTXN_DISCOUNT_MULTIPLIER', 0.4);

// Permissions.
$ttds = avtxns_txn_types();
foreach ($ttds as $ttd) {
  define('AVTXNS_PERM_CREATE_' . strtoupper($ttd['type']), 'avbase create transaction ' . $ttd['type']);
  define('AVTXNS_PERM_EDIT_' . strtoupper($ttd['type']), 'avbase edit transaction ' . $ttd['type']);
  define('AVTXNS_PERM_VIEW_' . strtoupper($ttd['type']), 'avbase view transaction ' . $ttd['type']);
  define('AVTXNS_PERM_VOID_' . strtoupper($ttd['type']), 'avbase void transaction ' . $ttd['type']);
  if (!empty($ttd['product_discount_check'])) {
    define('AVTXNS_PERM_OPEN_' . strtoupper($ttd['type']), 'avbase open transaction ' . $ttd['type']);
  }
}


/**
 * Implementation of hook_permission().
 */
function avtxns_permission() {
  $permissions = array();
  $ttds = avtxns_txn_types();
  foreach ($ttds as $td_k => $ttd) {
    $ttd_name = $ttd['name'];
    $ttd_type = strtoupper($ttd['type']);
    $permissions[constant('AVTXNS_PERM_CREATE_' . $ttd_type)] = array(
      'title' => t('@tdname - CREATE', array('@tdname' => $ttd_name)),
    );
    $permissions[constant('AVTXNS_PERM_EDIT_' . $ttd_type)] = array(
      'title' => t('@tdname - EDIT', array('@tdname' => $ttd_name)),
    );
    $permissions[constant('AVTXNS_PERM_VIEW_' . $ttd_type)] = array(
      'title' => t('@tdname - VIEW', array('@tdname' => $ttd_name)),
    );
    $permissions[constant('AVTXNS_PERM_VOID_' . $ttd_type)] = array(
      'title' => t('@tdname - VOID', array('@tdname' => $ttd_name)),
    );
    if (!empty($ttd['product_discount_check'])) {
      $permissions[constant('AVTXNS_PERM_OPEN_' . $ttd_type)] = array(
        'title' => t('@tdname - APPROVE', array('@tdname' => $ttd_name)),
        'description' => t('Approve pending @tdname', array('@tdname' => $ttd['plural_name'])),
      );
    }
  }
  return $permissions;
}

/**
 * Implementation of hook_menu().
 */
function avtxns_menu() {
  $items['av/transactions'] = array(
    'title' => 'Transactions',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('avtxns_txns_home_form'),
    'access callback' => 'user_is_logged_in',
    'menu_name' => 'av',
    'expanded' => TRUE,
  );
  $items['av/transactions/qty-check-and-reserve'] = array(
    'title' => 'QTY Check',
    'page callback' => 'avtxns_qty_check_and_reserve',
    'access callback' => 'user_is_logged_in',
    'file' => 'inc/helpers.inc',
    'type' => MENU_CALLBACK,
  );

  $transaction_types = avtxns_txn_types();
  foreach ($transaction_types as $k => $v) {
    $ttype = strtoupper($k);
    $items[$v['base_path']] = array(
      'title' => 'Transactions',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('avtxns_txns_home_form'),
      'access arguments' => array(constant('AVTXNS_PERM_VIEW_' . $ttype)),
    );
    $items["{$v['base_path']}/new"] = array(
      'title' => "New {$v['name']}",
      'page callback' => 'drupal_get_form',
      'page arguments' => array('avtxns_txn_form', $k, NULL),
      'access arguments' => array(constant('AVTXNS_PERM_CREATE_' . $ttype)),
      'type' => MENU_LOCAL_TASK,
      'file' => 'inc/txn.form.inc',
      'weight' => 10,
    );
    $items["{$v['base_path']}/%avtxns_txn/view"] = array(
      'title' => "View {$v['name']}",
      'page callback' => 'drupal_get_form',
      'page arguments' => array('avtxns_txn_form', $k, 2, TRUE),
      'access arguments' => array(constant('AVTXNS_PERM_VIEW_' . $ttype)),
      'type' => MENU_LOCAL_TASK,
      'file' => 'inc/txn.form.inc',
      'weight' => 0,
    );
    $items["{$v['base_path']}/%avtxns_txn/edit"] = array(
      'title' => "Edit {$v['name']}",
      'page callback' => 'drupal_get_form',
      'page arguments' => array('avtxns_txn_form', $k, 2),
      'access arguments' => array(constant('AVTXNS_PERM_EDIT_' . $ttype)),
      'type' => MENU_LOCAL_TASK,
      'file' => 'inc/txn.form.inc',
      'weight' => 1,
    );
  }

  $items['av/transactions/%avtxns_txn/change-status/%'] = array(
    'title' => 'Transaction Status Change',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('avtxns_txn_change_status_confirm_form', 2, 4),
    'access callback' => 'avtxns_txn_can_status_change',
    'access arguments' => array(2, 4),
    'type' => MENU_CALLBACK,
    'file' => 'inc/txn.form.inc',
  );

  return $items;
}

/**
 * Implementation of hook_theme().
 *
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 * @return array
 */
function avtxns_theme($existing, $type, $theme, $path) {
  $themes = array();

  $template_path = $path . '/templates';

  // FORMS.
  $theme_names = array(
    'avtxns_item_list_form',
    'avtxns_txn_list_filter_form',
    'avtxns_special_discount_form',
  );
  foreach ($theme_names as $theme_name) {
    $themes[$theme_name] = array(
      'render element' => 'form',
      'template' => str_replace('_', '-', $theme_name),
      'path' => $template_path,
    );
  }

  // OTHERS.
  $theme_names = array(
    'avtxns_txn_mail',
    'avtxns_txn_mail_table',
  );
  foreach ($theme_names as $theme_name) {
    $themes[$theme_name] = array(
      'variables' => array(),
      'template' => str_replace('_', '-', $theme_name),
      'path' => $template_path,
    );
  }

  return $themes;
}

/**
 * Implementation of hook_mail().
 * @param $key
 * @param $message
 * @param $params
 */
function avtxns_mail($key, &$message, $params) {
  switch ($key) {
    case 'transaction':
      $message['subject'] = t('Purchase Order from @site_name - P.O.# @transaction_id', array('@transaction_id' => $params['transaction_id'], '@site_name' => variable_get('site_name', 'UCT')));
      $message['body'] = theme('avtxns_txn_mail', $params);
      // Save a copy.
      //$message['headers']['CC'] = 'ucaretrading@gmail.com';
      break;
  }
}

/**
 * Transaction List page.
 * @param $form
 * @param $form_state
 * @return array
 */
function avtxns_txns_home_form($form, &$form_state) {
// Set autocomplete off.
  $form['#attributes']['autocomplete'] = 'off';
  $transaction_types = avtxns_txn_types();
  foreach ($transaction_types as $k => $type) {
    $ttype = strtoupper($k);
    $can_create = user_access(constant('AVTXNS_PERM_CREATE_' . $ttype));
    $button_color_class = $type['transaction'] == 'sales' ? 'uk-button-success' : 'uk-button-primary';
    $form["new_$k"] = array(
      '#markup' => l($type['name'], "{$transaction_types[$k]['base_path']}/new", array('attributes' => array('class' => array("uk-button uk-margin-small-right $button_color_class")))),
      '#access' => $can_create,
    );
  }
  //$form['new_po'] = array('#markup' => l('New purchase order', 'av/txns/po/new', array('attributes' => array('class' => array('uk-button', 'uk-button-primary')))));
  //$form['new_gr'] = array('#markup' => l('Receive items', 'av/txns/gr/new', array('attributes' => array('class' => array('uk-button', 'uk-button-primary', 'uk-margin-small-left')))));
  //$form['new_rept'] = array('#markup' => l('New purchase return', 'av/txns/rept/new', array('attributes' => array('class' => array('uk-button', 'uk-button-primary', 'uk-margin-small-left')))));
  //$form['new_so'] = array('#markup' => l('New sales order', 'av/txns/so/new', array('attributes' => array('class' => array('uk-button', 'uk-button-success', 'uk-margin-small-left')))));
  //$form['new_dr'] = array('#markup' => l('New delivery', 'av/txns/delivery/new', array('attributes' => array('class' => array('uk-button', 'uk-button-success', 'uk-margin-small-left')))));
  //$form['new_ret'] = array('#markup' => l('New sales return', 'av/txns/ret/new', array('attributes' => array('class' => array('uk-button', 'uk-button-success', 'uk-margin-small-left')))));
  //$form['new_sinv'] = array('#markup' => l('New invoice', 'av/txns/sinv/new', array('attributes' => array('class' => array('uk-button', 'uk-button-success', 'uk-margin-small-left')))));
  //$form['new_spay'] = array('#markup' => l('Receive payment', 'av/txns/spay/new', array('attributes' => array('class' => array('uk-button', 'uk-button-success', 'uk-margin-small-left')))));

  $form['txns_list'] = avtxns_txn_list_form($form, $form_state);
  return $form;
}

/**
 * Return list of transaction types.
 * @param string $type
 *
 * @return array
 */
function avtxns_txn_types($type = NULL) {
  $ret = &drupal_static(__FUNCTION__, array());
  if (empty($ret)) {
    // Purchase.
    $ret[AVTXNS_TXN_TYPE_PURCHASE_ORDER] = array(
      'type' => AVTXNS_TXN_TYPE_PURCHASE_ORDER,
      'base_path' => 'av/' . AVTXNS_TXN_TYPE_PURCHASE_ORDER,
      'transaction' => 'purchase',
      'name' => 'Purchase Order',
      'plural_name' => 'Purchase Orders',
      'ctd' => avclients_client_types(AVCLIENT_TYPE_VENDOR),
    );
    $ret[AVTXNS_TXN_TYPE_RECEIVE] = array(
      'type' => AVTXNS_TXN_TYPE_RECEIVE,
      'base_path' => 'av/' . AVTXNS_TXN_TYPE_RECEIVE,
      'transaction' => 'purchase',
      'name' => 'Received Items',
      'plural_name' => 'Received items',
      'ctd' => avclients_client_types(AVCLIENT_TYPE_VENDOR),
      'pending_txns_reference_type' => AVTXNS_TXN_TYPE_PURCHASE_ORDER,
      'qty_change' => 'increment',
      'cost_change' => TRUE,
      'product_discount_overwrite' => TRUE,
    );
    $ret[AVTXNS_TXN_TYPE_PURCHASE_RETURN] = array(
      'type' => AVTXNS_TXN_TYPE_PURCHASE_RETURN,
      'base_path' => 'av/' . AVTXNS_TXN_TYPE_PURCHASE_RETURN,
      'transaction' => 'purchase',
      'name' => 'Purchase Return',
      'plural_name' => 'Purchase Returns',
      'ctd' => avclients_client_types(AVCLIENT_TYPE_VENDOR),
      'qty_change' => 'decrement',
    );
    //$ret[AVTXNS_TXN_TYPE_CREATE_BILL] = array(
    //  'type' => AVTXNS_TXN_TYPE_CREATE_BILL,
    //  'base_path' => 'av/' . AVTXNS_TXN_TYPE_CREATE_BILL,
    //  'transaction' => 'purchase',
    //  'name' => 'Bill',
    //  'plural_name' => 'Bills',
    //  'ctd' => avclients_client_types(AVCLIENT_TYPE_VENDOR),
    //  'pending_txns_reference_type' => AVTXNS_TXN_TYPE_RECEIVE,
    //  'payable_type' => 'credit',
    //  //'client_statuses' => array(AVCLIENT_STATUS_ACTIVE),
    //  'bill' => TRUE,
    //);
    //$ret[AVTXNS_TXN_TYPE_PAY_BILL] = array(
    //  'type' => AVTXNS_TXN_TYPE_PAY_BILL,
    //  'base_path' => 'av/' . AVTXNS_TXN_TYPE_PAY_BILL,
    //  'transaction' => 'purchase',
    //  'name' => 'Bills Payment',
    //  'plural_name' => 'Paid Bills',
    //  'ctd' => avclients_client_types(AVCLIENT_TYPE_VENDOR),
    //  'pending_txns_reference_type' => AVTXNS_TXN_TYPE_CREATE_BILL,
    //  //'client_statuses' => array(AVCLIENT_STATUS_ACTIVE),
    //  'payment' => TRUE,
    //);

    // Sales.
    $ret[AVTXNS_TXN_TYPE_SALES_ORDER] = array(
      'type' => AVTXNS_TXN_TYPE_SALES_ORDER,
      'base_path' => 'av/' . AVTXNS_TXN_TYPE_SALES_ORDER,
      'transaction' => 'sales',
      'name' => 'Sales Order',
      'plural_name' => 'Sales Orders',
      'ctd' => avclients_client_types(AVCLIENT_TYPE_CUSTOMER),
    );
    $ret[AVTXNS_TXN_TYPE_DELIVERY] = array(
      'type' => AVTXNS_TXN_TYPE_DELIVERY,
      'base_path' => 'av/' . AVTXNS_TXN_TYPE_DELIVERY,
      'transaction' => 'sales',
      'name' => 'Delivery',
      'plural_name' => 'Deliveries',
      'ctd' => avclients_client_types(AVCLIENT_TYPE_CUSTOMER),
      'pending_txns_reference_type' => AVTXNS_TXN_TYPE_SALES_ORDER,
      'qty_change' => 'decrement',
      'cost_change' => TRUE,
      'product_discount_check' => TRUE,
      'receivable_type' => 'debit',
    );
    $ret[AVTXNS_TXN_TYPE_SALES_RETURN] = array(
      'type' => AVTXNS_TXN_TYPE_SALES_RETURN,
      'base_path' => 'av/' . AVTXNS_TXN_TYPE_SALES_RETURN,
      'transaction' => 'sales',
      'name' => 'Sales Return',
      'plural_name' => 'Sales Returns',
      'ctd' => avclients_client_types(AVCLIENT_TYPE_CUSTOMER),
      'pending_txns_reference_type' => AVTXNS_TXN_TYPE_DELIVERY,
      'qty_change' => 'increment',
      'receivable_type' => 'credit',
    );
    $ret[AVTXNS_TXN_TYPE_INVOICE] = array(
      'type' => AVTXNS_TXN_TYPE_INVOICE,
      'base_path' => 'av/' . AVTXNS_TXN_TYPE_INVOICE,
      'transaction' => 'sales',
      'name' => 'Invoice',
      'plural_name' => 'Invoices',
      'ctd' => avclients_client_types(AVCLIENT_TYPE_CUSTOMER),
      'pending_txns_reference_type' => AVTXNS_TXN_TYPE_DELIVERY,
      'receivable_type' => 'credit',
      'client_statuses' => array(AVCLIENT_STATUS_ACTIVE, AVCLIENT_STATUS_SUSPENDED),
      'bill' => TRUE,
    );
    $ret[AVTXNS_TXN_TYPE_PAYMENT] = array(
      'type' => AVTXNS_TXN_TYPE_PAYMENT,
      'base_path' => 'av/' . AVTXNS_TXN_TYPE_PAYMENT,
      'transaction' => 'sales',
      'name' => 'Received Payment',
      'plural_name' => 'Received Payment',
      'ctd' => avclients_client_types(AVCLIENT_TYPE_CUSTOMER),
      'pending_txns_reference_type' => AVTXNS_TXN_TYPE_INVOICE,
      'client_statuses' => array(AVCLIENT_STATUS_ACTIVE, AVCLIENT_STATUS_SUSPENDED),
      'payment' => TRUE,
    );
  }

  if (isset($ret[$type])) {
    return $ret[$type];
  }
  elseif (is_null($type)) {
    return $ret;
  }
  return NULL;
}

function avtxns_txn_list_form($form, &$form_state, $options = array()) {
  $form = array(
    '#visible_in_view_mode' => TRUE,
    //'#prefix' => '<div>'
  );

  if (empty($options['#hide_filter_form'])) {
    $filter_form_settings = array(
      'avtxn.id' => array('#access' => TRUE),
      'search_text' => array('#access' => TRUE),
      'avtxn.transaction_date' => array('#access' => TRUE),
      'avtxn.transaction_type' => array('#access' => TRUE),
      'avtxn.status' => array('#access' => TRUE),
    );
    $form['transaction_list_filter'] = avtxns_txn_list_filter_form(NULL, $form_state, $filter_form_settings);
    $form['transaction_list_filter']['search_text']['#attributes']['placeholder'] = 'search agent, customer, vendor';
  }
  $client_header = 'Customer / Vendor';
  //if (arg(1) == 'vendors') {
  //  $client_header = 'Vendor';
  //}
  //elseif (arg(1) == 'customers') {
  //  $client_header = 'Customer';
  //}
  $header = array(
    //'status' => array('data' => '&nbsp;', 'style' => 'width: 65px;'),
    'transaction_id' => array('data' => '#', 'field' => 'avtxn.id'),
    'date' => array('data' => 'Date', 'field' => 'avtxn.transaction_date'),
    'transaction_type' => array('data' => 'Type', 'field' => 'avtxn.transaction_type'),
    'client_name' => array('data' => $client_header, 'field' => 'avclients.display_name'),
    'agent_name' => array('data' => 'Agent', 'field' => 'avcat_agent.title'),
    'created_by' => array('data' => 'Created by', 'field' => 'u.name'),
  );

  if (!empty($options['#hide_filter_form'])) {
    foreach ($header as $h_k => $h) {
      unset($header[$h_k]['field']);
    }
  }

  $required_filter_query = empty($options['#filter_query']) ? array() : $options['#filter_query'];
  $user_filter = empty($form_state['values']['avtxns_tl_filter']) ? array() : $form_state['values']['avtxns_tl_filter'];
  $filter_query = empty($user_filter['filter_query']) ? array() : $user_filter['filter_query'];
  $filter_query = array_merge_recursive($filter_query, $required_filter_query);

  // Set table pagination and sort settings.
  if (!empty($user_filter['settings']['table_href'])) {
    $table_ajax_href = $user_filter['settings']['table_href'];
    $href_parts = parse_url($table_ajax_href);
    if (!empty($href_parts['query'])) {
      parse_str($href_parts['query'], $href_query);
      foreach ($href_query as $k => $v) {
        $_GET[$k] = $v;
      }
    }
  }

  $where = empty($filter_query['where']) ? array() : $filter_query['where'];
  $args = empty($filter_query['args']) ? array() : $filter_query['args'];
  $rows_per_page = empty($options['#hide_filter_form']) ? 20 : 10;
  $total_count = avtxns_txns_query_load($where, $args, NULL, NULL, NULL, array(), array(), array(), TRUE);
  $page = pager_default_initialize($total_count, $rows_per_page);
  $offset = $rows_per_page * $page;
  $order_by = avbase_build_header_order_array($header);
  $transactions = avtxns_txns_query_load($where, $args, $rows_per_page, $offset, $order_by);
  //$index = 0;
  $rows = array();
  foreach ($transactions as $row) {
    $sd = avtxns_txn_status_details($row->status);
    $row_class = '';
    $badge_html = '';
    $badge_class = '';
    $badge_icon_html = '';
    $badge_icon = '';
    switch ($row->status) {
      case AVTXNS_TXN_STATUS_PENDING:
        $row_class = 'uk-alert-warning';
        $badge_class = 'uk-badge-warning';
        $badge_icon = 'minus-circle';
        break;
      case AVTXNS_TXN_STATUS_VOID:
        $row_class = 'uk-row-mute';
        $badge_class = 'uk-badge-danger uk-badge-void';
        $badge_icon = 'minus-circle';
        break;
      case AVTXNS_TXN_STATUS_CLOSED:
        $badge_class = 'uk-badge-success';
        $badge_icon = 'lock';
        break;
    }
    if (!empty($badge_class)) {
      $badge_icon_html = '<i class="uk-icon-justify uk-icon-' . $badge_icon . '"></i>';
      $badge_html = empty($sd['title']) ? '' : ('<span title="' . $sd['title'] . '" class="uk-badge ' . $badge_class . ' uk-margin-small-right" style="position: relative; top: -2px;">' . $badge_icon_html . '</span>');
    }

    $created_by_user = array(
      'account' => (object) array('name' => $row->name, 'uid' => $row->uid),
    );
    if ($row->uid) {
      $created_by_user['link_path'] = "user/{$row->uid}";
    }
    $transaction_type = avtxns_txn_types($row->transaction_type);
    $view_path = "{$transaction_type['base_path']}/$row->id/view";
    $rows[$row->id] = array(
      'data' => array(
        //'status' => $badge_html,
        'transaction_id' => l($row->id, $view_path),
        'date' => l(format_date($row->transaction_date, 'custom', 'M d, Y'), $view_path),
        'transaction_type' => $badge_html . l($transaction_type['name'], $view_path),
        'client_name' => /*$rows[$index]['data'][] =*/ check_plain($row->display_name),
        'agent_name' => check_plain($row->agent_name),
        'created_by' => $row->uid ? theme('username', $created_by_user) : '',
      ),
      'class' => array($row_class),
    );
  }

  $table_attributes = array(
    'id' => 'transaction-list-table',
    'class' => array('uk-table-condensed'),
  );

  $pager_html = empty($options['#hide_filter_form']) ? theme('pager', array('tags' => array())) : '';
  $form['transaction_list_table'] = array(
    '#theme' => 'table',
    '#header' => $header,
    '#rows' => $rows,
    '#empty' => '<div class="uk-text-muted">' . t('No match found.') . '</div>',
    '#attributes' => $table_attributes,
    '#prefix' => '<div id="transaction-list-table-wrapper">',
    '#suffix' => $pager_html . '<!--Do not remove me.--></div>',
  );

  //if (empty($rows)) {
  //  $table_markup = '<div class="uk-margin-top uk-text-muted">No match found.</div>';
  //}
  //else {
  //  $table_markup = theme('table', array('header' => $header, 'rows' => $rows, 'attributes' => $table_attributes));
  //}
  //$form['transaction_list_table']['#markup'] = '<div id="transaction-list-table-wrapper">' . $table_markup . '<!--Do not remove me--></div>';
  return $form;
}

/**
 * Generic Transaction List Filter form.
 * @param $form
 * @param $form_state
 * @param array $settings
 *
 * @return mixed
 */
function avtxns_txn_list_filter_form($form, &$form_state, $settings = array()) {
  $fields = array(
    '#theme' => 'avtxns_txn_list_filter_form',
    '#tree' => TRUE,
    '#type' => 'container',
    '#attributes' => array(
      'id' => 'avtxns-txn-list-filter-form',
    ),
    '#attached' => array(
      'js' => array(AVTXNS_MODULE_PATH . '/js/transaction_list_filter.form.js'),
    ),
  );

  $fields['avtxn.id'] = empty($settings['avtxn.id']) ? array() : $settings['avtxn.id'];
  $fields['avtxn.id'] += array(
    '#type' => 'textfield',
    '#attributes' => array(
      'class' => array('trigger-ajax-search trigger-search-on-keyup'),
      'placeholder' => '#',
    ),
    '#icon_key' => 'search',
    '#access' => FALSE,
  );
  $fields['search_text'] = empty($settings['search_text']) ? array() : $settings['search_text'];
  $fields['search_text'] += array(
    '#type' => 'textfield',
    '#attributes' => array(
      'class' => array('trigger-ajax-search trigger-search-on-keyup'),
      'placeholder' => 'customer / vendor / agent name',
    ),
    '#icon_key' => 'search',
    '#access' => FALSE,
  );

  $fields['avcat_agent.title'] = empty($settings['avcat_agent.title']) ? array() : $settings['avcat_agent.title'];
  $fields['avcat_agent.title'] += array(
    '#type' => 'textfield',
    '#maxlength' => 255,
    '#attributes' => array(
      'placeholder' => 'filter by agent',
      'class' => array('trigger-ajax-search'),
    ),
    '#access' => FALSE,
  );

  $fields['avcat_area.title'] = empty($settings['avcat_area.title']) ? array() : $settings['avcat_area.title'];
  $fields['avcat_area.title'] += array(
    '#title' => 'Area',
    '#type' => 'textfield',
    '#maxlength' => 255,
    '#attributes' => array(
      'class' => array('trigger-ajax-search'),
    ),
    '#autocomplete_path' => 'av/categories/area/autocomplete',
    '#access' => FALSE,
  );

  $fields['avcat_principal.title'] = empty($settings['avcat_principal.title']) ? array() : $settings['avcat_principal.title'];
  $fields['avcat_principal.title'] += array(
    '#type' => 'textfield',
    '#maxlength' => 255,
    '#attributes' => array(
      'class' => array('trigger-ajax-search'),
    ),
    '#access' => FALSE,
  );

  $fields['avclients.display_name'] = empty($settings['avclients.display_name']) ? array() : $settings['avclients.display_name'];
  $fields['avclients.display_name'] += array(
    '#type' => 'textfield',
    '#maxlength' => 255,
    '#attributes' => array(
      'class' => array('trigger-ajax-search'),
    ),
    '#access' => FALSE,
  );



  //$date_format = 'M. d, Y';
  $fields['avtxn.transaction_date'] = empty($settings['avtxn.transaction_date']) ? array() : $settings['avtxn.transaction_date'];
  $fields['avtxn.transaction_date'] += array(
    '#type' => 'textfield',
    //'#default_value' => !empty($row->expiry_date) ? format_date($row->expiry_date, 'custom', $date_format) : '',
    //'#element_validate' => array('avbase_element_validate_date'),
    //'#av_date_format' => $date_format,
    '#icon_key' => 'calendar',
    '#attributes' => array(
      'data-uk-datepicker' => "{format:'MMMM DD, YYYY'}",
      'class' => array('trigger-ajax-search'),
      'readonly' => 'readonly',
    ),
    '#access' => FALSE,
  );

  $fields['date_to'] = empty($settings['date_to']) ? array() : $settings['date_to'];
  $fields['date_to'] += array(
    '#type' => 'textfield',
    '#icon_key' => 'calendar',
    '#attributes' => array(
      'data-uk-datepicker' => "{format:'MMMM DD, YYYY'}",
      'class' => array('trigger-ajax-search'),
      'readonly' => 'readonly',
    ),
    '#access' => FALSE,
  );
  $fields['date_from'] = empty($settings['date_from']) ? array() : $settings['date_from'];
  $fields['date_from'] += array(
    '#type' => 'textfield',
    '#icon_key' => 'calendar',
    '#attributes' => array(
      'data-uk-datepicker' => "{format:'MMMM DD, YYYY'}",
      'class' => array('trigger-ajax-search'),
      'readonly' => 'readonly',
    ),
    '#access' => FALSE,
  );

  $fields['avtxn.transaction_type'] = empty($settings['avtxn.transaction_type']) ? array() : $settings['avtxn.transaction_type'];
  $fields['avtxn.transaction_type'] += array(
    '#type' => 'select',
    '#options' => avtxns_txn_types_options_array(),
    '#empty_value' => '',
    '#empty_option' => '- transaction type -',
    '#attributes' => array(
      'class' => array('trigger-ajax-search'),
    ),
    '#access' => FALSE,
  );

  $fields['avtxn.status'] = empty($settings['avtxn.status']) ? array() : $settings['avtxn.status'];
  $fields['avtxn.status'] += array(
    '#type' => 'select',
    '#options' => avtxns_txn_status_options_array(),
    '#empty_value' => '',
    '#empty_option' => '- status -',
    '#attributes' => array(
      'class' => array('trigger-ajax-search'),
    ),
    '#access' => FALSE,
  );

  // Set fields' resistance to reset button.
  //foreach ($fields as $k => $v) {
  //
  //}

  // Buttons.
  $fields['buttons']['reset_button'] = empty($settings['reset_button']) ? array() : $settings['reset_button'];
  $fields['buttons']['reset_button'] += array(
    '#id' => 'transaction-reset-btn',
    '#type' => 'submit',
    '#value' => t('reset filter'),
    //'#button_label' => '<i class="uk-icon-remove"></i>',
  );

  $fields['buttons']['search_button'] = empty($settings['search_button']) ? array() : $settings['search_button'];
  $fields['buttons']['search_button'] += array(
    '#id' => 'transaction-search-btn',
    '#type' => 'submit',
    '#value' => t('Search'),
    '#submit' => array('avtxns_txn_list_filter_form_submit'),
    '#limit_validation_errors' => array(array('avtxns_tl_filter')),
    '#attributes' => array(
      'class' => array('uk-hidden')
    ),
    '#ajax' => array(
      'callback' => 'avtxns_txn_form_ajax_search',
      'wrapper' => 'transaction-list-table-wrapper',
      'effect' => 'none',
      'event' => 'click',
      'progress' => array(),
    ),
  );

  $fields['settings']['table_href'] = array(
    '#type' => 'hidden',
    '#attributes' => array(
      'id' => 'transaction-list-table-href',
      'class' => array('trigger-ajax-search'),
    ),
  );

  $form['avtxns_tl_filter'] = $fields;
  return $form;
}

function avtxns_txn_list_filter_form_submit($form, &$form_state) {
  $form_state['rebuild'] = TRUE;
  $filter_values = empty($form_state['values']['avtxns_tl_filter']) ? array() : $form_state['values']['avtxns_tl_filter'];
  $arg_index = 0;
  $where = $args = array();
  $query_exceptions = empty($form['#transaction_query_exceptions']) ? array() : $form['#transaction_query_exceptions'];
  foreach ($filter_values as $k => $v) {
    if ($k == 'buttons' || $k == 'settings') {
      continue;
    }
    $query_field_aliases = empty($query_exceptions[$k]['#query_field_aliases']) ? array() : $query_exceptions[$k]['#query_field_aliases'];
    $v = trim($v);
    $arg_name = 'arg_' . $arg_index++;
    if ($k == 'search_text' && $v != '') {
      $or = array();
      $or[] = "avcat_agent.title LIKE :$arg_name";
      $or[] = "avclients.display_name LIKE :$arg_name";
      $where[] = '(' . implode(' OR ', $or) . ')';
      $args[":$arg_name"] = '%' . db_like($v) . '%';
      continue;
    }
    elseif ($k == 'avtxn.transaction_date' && $v != '') {
      $timestamp = strtotime($v);
      if (empty($timestamp)) {
        continue;
      }
      $next_day_timestamp = strtotime('+1 day', $timestamp);
      $where[] = 'avtxn.transaction_date >= :stamp1 AND avtxn.transaction_date < :stamp2';
      $args[':stamp1'] = $timestamp;
      $args[':stamp2'] = $next_day_timestamp;
      continue;
    }
    elseif ($k == 'date_to' && $v != '') {
      $timestamp = strtotime($v);
      if (empty($timestamp)) {
        continue;
      }
      $next_day_timestamp = strtotime('+1 day', $timestamp);
      //$query_field_aliases = empty($query_exceptions[$k]['#query_field_aliases']) ? array() : $query_exceptions[$k]['#query_field_aliases'];
      if (!empty($query_field_aliases)) {
        $this_or = array();
        foreach ($query_field_aliases as $qfa) {
          $this_or[] = "$qfa < :stamp2";
        }
        if (!empty($this_or)) {
          $where[] = '(' . implode(' OR ', $this_or) . ')';
        }
      }
      else {
        $where[] = 'avtxn.transaction_date < :stamp2';
      }
      $args[':stamp2'] = $next_day_timestamp;
      continue;
    }
    elseif ($k == 'date_from' && $v != '') {
      $timestamp = strtotime($v);
      if (empty($timestamp)) {
        continue;
      }
      //$query_field_aliases = empty($query_exceptions[$k]['#query_field_aliases']) ? array() : $query_exceptions[$k]['#query_field_aliases'];
      if (!empty($query_field_aliases)) {
        $this_or = array();
        foreach ($query_field_aliases as $qfa) {
          $this_or[] = "$qfa >= :stamp_from";
        }
        if (!empty($this_or)) {
          $where[] = '(' . implode(' OR ', $this_or) . ')';
        }
      }
      else {
        $where[] = 'avtxn.transaction_date >= :stamp_from';
      }
      $args[':stamp_from'] = $timestamp;
      continue;
    }

    if ($v != '') {
      if (!empty($query_field_aliases)) {
        $this_or = array();
        foreach ($query_field_aliases as $qfa) {
          $this_or[] = "$qfa = :$arg_name";
        }
        if (!empty($this_or)) {
          $where[] = '(' . implode(' OR ', $this_or) . ')';
        }
      }
      else {
        $where[] = "{$k} = :$arg_name";
      }
      $args[":$arg_name"] = $v;
    }
  }

  $form_state['values']['avtxns_tl_filter']['filter_query'] = array('where' => $where, 'args' => $args);
}


function avtxns_txn_form_ajax_search($form, $form_state) {
  $trigger = $form_state['triggering_element'];


  switch ($trigger['#id']) {
    case 'transaction-search-btn':
      $target_table_parents = $trigger['#array_parents'];
      $depth = count($target_table_parents) - 4;
      if ($depth > 0) {
        $target_table_parents = array_slice($target_table_parents, 0, $depth);
      }
      else {
        $target_table_parents = empty($trigger['#table_parents']) ? array() : $trigger['#table_parents'];
      }
      $target_table_parents[] = 'transaction_list_table';
      $transaction_list_form = drupal_array_get_nested_value($form, $target_table_parents);
      //dpm($form);
      //dpm($target_table_parents);
      //dpm($transaction_list_form);
      //return $form;
      return $transaction_list_form;
      break;
  }

  return $form;
}

/**
 * Check if user is allowed to change transaction status.
 * @param $transaction
 * @param $status
 * @return bool
 */
function avtxns_txn_can_status_change($transaction, $status) {
  if (empty($transaction->transaction_type)) {
    return FALSE;
  }

  $transaction_type = strtoupper($transaction->transaction_type);

  if ($status == AVTXNS_TXN_STATUS_VOID) {
    return user_access(constant('AVTXNS_PERM_VOID_' . $transaction_type));
  }
  elseif ($status == AVTXNS_TXN_STATUS_OPEN || $status == AVTXNS_TXN_STATUS_PENDING) {
    return user_access(constant('AVTXNS_PERM_OPEN_' . $transaction_type));
  }
  else {
    return TRUE;
  }
}

