<?php

/**
 * @file
 * AV Vendors module.
 */

define('AVVENDORS_MODULE_PATH', drupal_get_path('module', 'avvendors'));
define('AVVENDORS_CATEGORY_SUPPLIER', 1);
define('AVVENDORS_CATEGORY_EXPENSES', 2);

require_once 'inc/helpers.inc';

/**
 * Implementation of hook_menu().
 */
function avvendors_menu() {
  $items['av/vendors'] = array(
    'title' => 'Vendors',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('avbase_entity_overview_form', 'vendors'),
    'access callback' => 'user_is_logged_in',
    'menu_name' => 'av',
    'expanded' => TRUE,
  );
  $items['av/vendors/autocomplete'] = array(
    'title' => 'Vendors Autocomplete',
    'page callback' => 'avvendors_autocomplete',
    'access callback' => 'user_is_logged_in',
    'type' => MENU_CALLBACK,
    'file' => 'inc/helpers.inc',
  );
  $items['av/vendors/add'] = array(
    'title' => 'New vendor',
    'page callback' => 'avvendors_vendor_form_load',
    'page arguments' => array(NULL),
    'access callback' => 'user_is_logged_in',
    'type' => MENU_LOCAL_TASK,
    'file' => 'inc/crud.inc',
    'weight' => 10,
  );
  $items['av/vendors/%avvendor/view'] = array(
    'title' => 'View',
    'page callback' => 'avvendors_vendor_form_load',
    'page arguments' => array(2, TRUE),
    'access callback' => 'user_is_logged_in',
    'type' => MENU_LOCAL_TASK,
    'file' => 'inc/crud.inc',
    'weight' => 0,
  );
  $items['av/vendors/%avvendor/edit'] = array(
    'title' => 'Edit',
    'page callback' => 'avvendors_vendor_form_load',
    'page arguments' => array(2),
    'access callback' => 'user_is_logged_in',
    'type' => MENU_LOCAL_TASK,
    'file' => 'inc/crud.inc',
    'weight' => 2,
  );
  $items['av/vendors/%avvendor/delete'] = array(
    'title' => 'Delete',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('avvendors_vendor_delete_confirm_form', 2),
    'access callback' => 'user_is_logged_in',
    'type' => MENU_CALLBACK,
    'file' => 'inc/crud.inc',
    'weight' => 3,
  );
  return $items;
}

/**
 * Implementation of hook_theme().
 *
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 * @return array
 */
function avvendors_theme($existing, $type, $theme, $path) {
  $forms_template_path = $path . '/templates';
  $form_names = array(
    'avvendors_vendor_form',
    'avvendors_home_form',
  );

  $theme_forms = array();
  foreach ($form_names as $form_name) {
    $theme_forms[$form_name] = array(
      'render element' => 'form',
      'template' => str_replace('_', '-', $form_name),
      'path' => $forms_template_path,
    );
  }

  return $theme_forms;
}

/**
 * Vendors homepage form.
 *
 * @param $form
 * @param $form_state
 * @return array
 */
function avvendors_home_form($form, &$form_state) {
//  drupal_add_js('sites/all/libraries/ag-grid/ag-grid.min.js');
//  drupal_add_js(AVVENDORS_MODULE_PATH . '/js/avvendors.js');

  $form = avbase_entity_overview_form($form, $form_state);
  return $form;

  $btn_options = array('attributes' => array('class' => AV_STYLE_CLASS_BTN . ' ' . AV_STYLE_CLASS_BTN_PRIMARY));
  $form['new_button'] = array('#markup' => l('New vendor', 'av/vendors/add', $btn_options));

  $header = array(
    array('data' => 'ID', 'field' => 'id', 'sort' => 'desc', 'class' => array('uk-hidden')),
    array('data' => 'Vendor / Company', 'field' => 'display_name'),
    array('data' => 'Category', 'field' => 'category_id'),
    array('data' => 'E-mail', 'field' => 'email'),
    array('data' => 'Name', 'field' => 'first_name'),
//    array('data' => 'Contact', 'field' => ''),
    '&nbsp;',
  );

  $rows = array();
  $result = db_select('avtbl_vendors', 'av')
    ->fields('av')
    ->extend('PagerDefault')
    ->extend('TableSort')
    ->limit(10)
    ->orderByHeader($header)
    ->execute();

  $action_links_all = array();
  $categories = avvendors_get_vendor_categories();
  foreach ($result as $row) {
    $menu_prefix = 'av/vendors/' . $row->id;
    $action_links = array('links' => array(
      'edit' => array('title' => 'edit', 'href' => $menu_prefix . '/edit', 'icon_kedy' => 'edit', 'query' => drupal_get_destination()),
      //'delete' => array('title' => 'delete', 'href' => $menu_prefix . '/delete', 'icond_key' => 'remove', 'query' => drupal_get_destination()),
    ));

    $action_links_all[] = $action_links;
    $actions_html = theme('links__bare', $action_links);
    $linked_name = l($row->display_name, $menu_prefix . '/view');
    $rows[] = array(
    'data' => array(
      'id' => array('data' => $row->id, 'class' => array('uk-hidden')),
      'display_name' => $linked_name . '<span class="uk-text-muted"> / ' . check_plain($row->company) .  '</span>',
      'category_id' => isset($categories[$row->category_id]) ? check_plain($categories[$row->category_id]) : '',
      'email' => check_plain($row->email),
      'first_name' => check_plain($row->first_name),
//    'display_name' => '',
      'actions' => $actions_html,
    ),
    'class' => array('uk-table-middle'),
    );
  }

  $table_attributes = array('id' => 'vendors-list-table');
  if (empty($rows)) {
    $table_markup = '<p>Nothing recorded yet.</p>';
  }
  else {
    $table_markup = theme('table', array('header' => $header, 'rows' => $rows, 'attributes' => $table_attributes, 'action_links_all' => $action_links_all));
  }
  $form['table']['#markup'] = $table_markup;
  $form['pager']['#markup'] = theme('pager', array('tags' => array()));
//$form['#after_build'] = array('avvendors_home_form_after_build');
//  $form['ag-grid']['#markup'] = '<div id="myGrid" style="height: 300px;" class="ag-fresh"></div>';
  return $form;
}

function avvendors_home_form_after_build($form, &$form_state) {
  dpm('f');
  dpm($form);
  return $form;
}
