<?php

/**
 * @file
 * AV Customers module.
 */

define('AVCUSTOMERS_MODULE_PATH', drupal_get_path('module', 'avcustomers'));

/**
 * Implementation of hook_menu().
 */
function avcustomers_menu() {
  $items['av/customers'] = array(
    'title' => 'Customers',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('avcustomers_home_form'),
    'access callback' => 'user_is_logged_in',
    'menu_name' => 'av',
    'expanded' => TRUE,
  );
  $items['av/customers/add'] = array(
    'title' => 'New Customer',
    'page callback' => 'avcustomers_new',
    'access callback' => 'user_is_logged_in',
    'menu_name' => 'av',
    'expanded' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'inc/crud.inc',
  );
  return $items;
}

/**
 * Implementation of hook_theme().
 *
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 * @return array
 */
function avcustomers_theme($existing, $type, $theme, $path) {
  $forms_template_path = $path . '/templates/forms';
  $form_names = array(
    'avcustomers_new_form',
    'avcustomers_home_form',
  );

  $theme_forms = array();
  foreach ($form_names as $form_name) {
    $theme_forms[$form_name] = array(
      'render element' => 'form',
      'template' => str_replace('_', '-', $form_name),
      'path' => $forms_template_path,
    );
  }

  return $theme_forms;
}

/**
 * Customers homepage form.
 *
 * @param $form
 * @param $form_state
 * @return array
 */
function avcustomers_home_form($form, &$form_state) {
//  drupal_add_js('sites/all/libraries/ag-grid/ag-grid.min.js');
//  drupal_add_js(AVCUSTOMERS_MODULE_PATH . '/js/avcustomers.js');

  $btn_options = array('attributes' => array('class' => AV_STYLE_CLASS_BTN . ' ' . AV_STYLE_CLASS_BTN_PRIMARY));
  $form['new_button'] = array('#markup' => l('New customer', 'av/customers/add', $btn_options));

  $header = array(
    array('data' => 'Customer', 'field' => 'display_name'),
    array('data' => 'Company', 'field' => 'company'),
    array('data' => 'Name', 'field' => 'first_name'),
//    array('data' => 'Contact', 'field' => ''),
    '&nbsp;',
  );

  $rows = array();
  $result = db_select('avtbl_customers', 'ac')
    ->fields('ac')
    ->extend('PagerDefault')
    ->extend('TableSort')
    ->limit(10)
    ->orderByHeader($header)
    ->execute();

  $action_links_all = array();
  foreach ($result as $row) {
    $action_links = array('links' => array(
      'edit' => array('title' => 'edit', 'href' => 'av/customers/' . $row->id . '/edit', 'icon_key' => 'edit'),
      'delete' => array('title' => 'delete', 'href' => 'av/customers/' . $row->id . '/delete', 'icon_key' => 'remove'),
    ));

    $action_links_all[] = $action_links;
    $actions_html = theme('links__button_group', $action_links);
    $rows[] = array(
    'data' => array(
      'display_name' => check_plain($row->display_name),
      'company' => check_plain($row->company),
      'first_name' => check_plain($row->first_name),
//    'display_name' => '',
      'actions' => $actions_html,
    ),
    'class' => array('uk-table-middle'),
    );
  }

  $table_attributes = array('id' => 'customers-list-table');
  $form['table']['#markup'] = theme('table', array('header' => $header, 'rows' => $rows, 'attributes' => $table_attributes, 'action_links_all' => $action_links_all));
  $form['pager']['#markup'] = theme('pager', array('tags' => array()));
//$form['#after_build'] = array('avcustomers_home_form_after_build');
//  $form['ag-grid']['#markup'] = '<div id="myGrid" style="height: 300px;" class="ag-fresh"></div>';
  return $form;
}

function avcustomers_home_form_after_build($form, &$form_state) {
  dpm('f');
  dpm($form);
  return $form;
}
